from app.schemas.dnd_class import DndClassCreate, ClassLevelCreate
from app.models.dnd_class import DndClass as DndClassModel, ClassLevel as ClassLevelModel 
# Path: api/app/game_data/classes_data.py
# This file contains the predefined data for all 12 SRD D&D classes and their level progressions.

PREDEFINED_CLASSES_DATA = [
    # --- Barbarian ---
    {
        "class_data": {"name": "Barbarian", "description": "A fierce warrior who can enter a battle rage.", "hit_die": 12},
        "levels": [
            {"level": 1, "proficiency_bonus": 2, "features": [{"name": "Rage", "desc": "You can enter a rage as a bonus action. While raging, you gain benefits if you aren't wearing heavy armor. You have 2 rage uses per day."}, {"name": "Unarmored Defense", "desc": "While you are not wearing any armor, your Armor Class equals 10 + your Dexterity modifier + your Constitution modifier."}]},
            {"level": 2, "proficiency_bonus": 2, "features": [{"name": "Reckless Attack", "desc": "You can throw aside all concern for defense to attack with fierce desperation. When you make your first attack on your turn, you can decide to attack recklessly. Doing so gives you advantage on melee weapon attack rolls using Strength during this turn, but attack rolls against you have advantage until your next turn."}, {"name": "Danger Sense", "desc": "You have advantage on Dexterity saving throws against effects that you can see, such as traps and spells."}]},
            {"level": 3, "proficiency_bonus": 2, "features": [{"name": "Primal Path", "desc": "You choose a path that shapes the nature of your rage. The Path of the Berserker is detailed in the SRD."}, {"name": "Rage", "desc": "You can now rage 3 times per day."}]},
            {"level": 4, "proficiency_bonus": 2, "features": [{"name": "Ability Score Improvement", "desc": "You can increase one ability score by 2, or two ability scores by 1."}]},
            {"level": 5, "proficiency_bonus": 3, "features": [{"name": "Extra Attack", "desc": "You can attack twice, instead of once, whenever you take the Attack action on your turn."}, {"name": "Fast Movement", "desc": "Your speed increases by 10 feet while you aren't wearing heavy armor."}]},
            {"level": 6, "proficiency_bonus": 3, "features": [{"name": "Path Feature", "desc": "You gain a feature from your Primal Path."}, {"name": "Rage", "desc": "You can now rage 4 times per day."}]},
            {"level": 7, "proficiency_bonus": 3, "features": [{"name": "Feral Instinct", "desc": "Your instincts are so honed that you have advantage on initiative rolls."}]},
            {"level": 8, "proficiency_bonus": 3, "features": [{"name": "Ability Score Improvement", "desc": "You can increase one ability score by 2, or two ability scores by 1."}]},
            {"level": 9, "proficiency_bonus": 4, "features": [{"name": "Brutal Critical (1 die)", "desc": "You can roll one additional weapon damage die when determining the extra damage for a critical hit with a melee attack."}, {"name": "Rage", "desc": "Your rage damage bonus increases to +3."}]},
            {"level": 10, "proficiency_bonus": 4, "features": [{"name": "Path Feature", "desc": "You gain a feature from your Primal Path."}]},
            {"level": 11, "proficiency_bonus": 4, "features": [{"name": "Relentless Rage", "desc": "If you drop to 0 hit points while you're raging and don't die outright, you can make a DC 10 Constitution saving throw. If you succeed, you drop to 1 hit point instead."}]},
            {"level": 12, "proficiency_bonus": 4, "features": [{"name": "Ability Score Improvement", "desc": "You can increase one ability score by 2, or two ability scores by 1."}, {"name": "Rage", "desc": "You can now rage 5 times per day."}]},
            {"level": 13, "proficiency_bonus": 5, "features": [{"name": "Brutal Critical (2 dice)", "desc": "You can roll two additional weapon damage dice when determining the extra damage for a critical hit with a melee attack."}]},
            {"level": 14, "proficiency_bonus": 5, "features": [{"name": "Path Feature", "desc": "You gain a feature from your Primal Path."}]},
            {"level": 15, "proficiency_bonus": 5, "features": [{"name": "Persistent Rage", "desc": "Your rage is so fierce that it ends early only if you fall unconscious or if you choose to end it."}]},
            {"level": 16, "proficiency_bonus": 5, "features": [{"name": "Ability Score Improvement", "desc": "You can increase one ability score by 2, or two ability scores by 1."}, {"name": "Rage", "desc": "Your rage damage bonus increases to +4."}]},
            {"level": 17, "proficiency_bonus": 6, "features": [{"name": "Brutal Critical (3 dice)", "desc": "You can roll three additional weapon damage dice when determining the extra damage for a critical hit with a melee attack."}, {"name": "Rage", "desc": "You can now rage 6 times per day."}]},
            {"level": 18, "proficiency_bonus": 6, "features": [{"name": "Indomitable Might", "desc": "If your total for a Strength check is less than your Strength score, you can use that score in place of the total."}]},
            {"level": 19, "proficiency_bonus": 6, "features": [{"name": "Ability Score Improvement", "desc": "You can increase one ability score by 2, or two ability scores by 1."}]},
            {"level": 20, "proficiency_bonus": 6, "features": [{"name": "Primal Champion", "desc": "Your Strength and Constitution scores increase by 4. Your maximum for those scores is now 24."}, {"name": "Rage", "desc": "You can rage an unlimited number of times."}]},
        ]
    },
    # --- Bard ---
    {
        "class_data": {"name": "Bard", "description": "An inspiring magician whose power echoes the music of creation.", "hit_die": 8},
        "levels": [
            {"level": 1, "proficiency_bonus": 2, "features": [{"name": "Spellcasting"}, {"name": "Bardic Inspiration (d6)"}], "spellcasting": {"cantrips_known": 2, "spells_known": 4, "spell_slots_level_1": 2}},
            {"level": 2, "proficiency_bonus": 2, "features": [{"name": "Jack of All Trades"}, {"name": "Song of Rest (d6)"}], "spellcasting": {"spells_known": 5, "spell_slots_level_1": 3}},
            {"level": 3, "proficiency_bonus": 2, "features": [{"name": "Bard College"}, {"name": "Expertise"}], "spellcasting": {"spells_known": 6, "spell_slots_level_2": 2}},
            {"level": 4, "proficiency_bonus": 2, "features": [{"name": "Ability Score Improvement"}], "spellcasting": {"cantrips_known": 3, "spells_known": 7, "spell_slots_level_2": 3}},
            {"level": 5, "proficiency_bonus": 3, "features": [{"name": "Bardic Inspiration (d8)"}, {"name": "Font of Inspiration"}], "spellcasting": {"spells_known": 8, "spell_slots_level_3": 2}},
            {"level": 6, "proficiency_bonus": 3, "features": [{"name": "Countercharm"}, {"name": "Bard College Feature"}], "spellcasting": {"spells_known": 9, "spell_slots_level_3": 3}},
            {"level": 7, "proficiency_bonus": 3, "features": [], "spellcasting": {"spells_known": 10, "spell_slots_level_4": 1}},
            {"level": 8, "proficiency_bonus": 3, "features": [{"name": "Ability Score Improvement"}], "spellcasting": {"spells_known": 11, "spell_slots_level_4": 2}},
            {"level": 9, "proficiency_bonus": 4, "features": [{"name": "Song of Rest (d8)"}], "spellcasting": {"spells_known": 12, "spell_slots_level_5": 1}},
            {"level": 10, "proficiency_bonus": 4, "features": [{"name": "Bardic Inspiration (d10)"}, {"name": "Expertise"}, {"name": "Magical Secrets"}], "spellcasting": {"cantrips_known": 4, "spells_known": 14, "spell_slots_level_5": 2}},
            {"level": 11, "proficiency_bonus": 4, "features": [], "spellcasting": {"spells_known": 15, "spell_slots_level_6": 1}},
            {"level": 12, "proficiency_bonus": 4, "features": [{"name": "Ability Score Improvement"}]},
            {"level": 13, "proficiency_bonus": 5, "features": [{"name": "Song of Rest (d10)"}], "spellcasting": {"spells_known": 16, "spell_slots_level_7": 1}},
            {"level": 14, "proficiency_bonus": 5, "features": [{"name": "Magical Secrets"}, {"name": "Bard College Feature"}]},
            {"level": 15, "proficiency_bonus": 5, "features": [{"name": "Bardic Inspiration (d12)"}], "spellcasting": {"spells_known": 18, "spell_slots_level_8": 1}},
            {"level": 16, "proficiency_bonus": 5, "features": [{"name": "Ability Score Improvement"}]},
            {"level": 17, "proficiency_bonus": 6, "features": [{"name": "Song of Rest (d12)"}], "spellcasting": {"spells_known": 19, "spell_slots_level_9": 1}},
            {"level": 18, "proficiency_bonus": 6, "features": [{"name": "Magical Secrets"}], "spellcasting": {"spells_known": 20}},
            {"level": 19, "proficiency_bonus": 6, "features": [{"name": "Ability Score Improvement"}]},
            {"level": 20, "proficiency_bonus": 6, "features": [{"name": "Superior Inspiration"}]},
        ]
    },
    # --- Cleric ---
    {
        "class_data": {"name": "Cleric", "description": "A priestly champion who wields divine magic in service of a higher power.", "hit_die": 8},
        "levels": [
            {"level": 1, "proficiency_bonus": 2, "features": [{"name": "Spellcasting"}, {"name": "Divine Domain"}], "spellcasting": {"cantrips_known": 3, "spell_slots_level_1": 2}},
            {"level": 2, "proficiency_bonus": 2, "features": [{"name": "Channel Divinity (1/rest)"}, {"name": "Divine Domain Feature"}], "spellcasting": {"spell_slots_level_1": 3}},
            {"level": 3, "proficiency_bonus": 2, "features": [], "spellcasting": {"spell_slots_level_2": 2}},
            {"level": 4, "proficiency_bonus": 2, "features": [{"name": "Ability Score Improvement"}], "spellcasting": {"cantrips_known": 4, "spell_slots_level_2": 3}},
            {"level": 5, "proficiency_bonus": 3, "features": [{"name": "Destroy Undead (CR 1/2)"}], "spellcasting": {"spell_slots_level_3": 2}},
            {"level": 6, "proficiency_bonus": 3, "features": [{"name": "Channel Divinity (2/rest)"}, {"name": "Divine Domain Feature"}], "spellcasting": {"spell_slots_level_3": 3}},
            {"level": 7, "proficiency_bonus": 3, "features": [], "spellcasting": {"spell_slots_level_4": 1}},
            {"level": 8, "proficiency_bonus": 3, "features": [{"name": "Ability Score Improvement"}, {"name": "Destroy Undead (CR 1)"}, {"name": "Divine Domain Feature"}], "spellcasting": {"spell_slots_level_4": 2}},
            {"level": 9, "proficiency_bonus": 4, "features": [], "spellcasting": {"spell_slots_level_5": 1}},
            {"level": 10, "proficiency_bonus": 4, "features": [{"name": "Divine Intervention"}], "spellcasting": {"cantrips_known": 5, "spell_slots_level_5": 2}},
            {"level": 11, "proficiency_bonus": 4, "features": [{"name": "Destroy Undead (CR 2)"}], "spellcasting": {"spell_slots_level_6": 1}},
            {"level": 12, "proficiency_bonus": 4, "features": [{"name": "Ability Score Improvement"}]},
            {"level": 13, "proficiency_bonus": 5, "features": [], "spellcasting": {"spell_slots_level_7": 1}},
            {"level": 14, "proficiency_bonus": 5, "features": [{"name": "Destroy Undead (CR 3)"}]},
            {"level": 15, "proficiency_bonus": 5, "features": [], "spellcasting": {"spell_slots_level_8": 1}},
            {"level": 16, "proficiency_bonus": 5, "features": [{"name": "Ability Score Improvement"}]},
            {"level": 17, "proficiency_bonus": 6, "features": [{"name": "Destroy Undead (CR 4)"}, {"name": "Divine Domain Feature"}], "spellcasting": {"spell_slots_level_9": 1}},
            {"level": 18, "proficiency_bonus": 6, "features": [{"name": "Channel Divinity (3/rest)"}]},
            {"level": 19, "proficiency_bonus": 6, "features": [{"name": "Ability Score Improvement"}]},
            {"level": 20, "proficiency_bonus": 6, "features": [{"name": "Divine Intervention Improvement"}]},
        ]
    },
    # --- Druid ---
    {
        "class_data": {"name": "Druid", "description": "A priest of the Old Faith, wielding the powers of nature and adopting animal forms.", "hit_die": 8},
        "levels": [
            {"level": 1, "proficiency_bonus": 2, "features": [{"name": "Druidic"}, {"name": "Spellcasting"}], "spellcasting": {"cantrips_known": 2, "spell_slots_level_1": 2}},
            {"level": 2, "proficiency_bonus": 2, "features": [{"name": "Wild Shape"}, {"name": "Druid Circle"}], "spellcasting": {"spell_slots_level_1": 3}},
            {"level": 3, "proficiency_bonus": 2, "features": [], "spellcasting": {"spell_slots_level_2": 2}},
            {"level": 4, "proficiency_bonus": 2, "features": [{"name": "Wild Shape Improvement"}, {"name": "Ability Score Improvement"}], "spellcasting": {"cantrips_known": 3, "spell_slots_level_2": 3}},
            {"level": 5, "proficiency_bonus": 3, "features": [], "spellcasting": {"spell_slots_level_3": 2}},
            {"level": 6, "proficiency_bonus": 3, "features": [{"name": "Druid Circle Feature"}], "spellcasting": {"spell_slots_level_3": 3}},
            {"level": 7, "proficiency_bonus": 3, "features": [], "spellcasting": {"spell_slots_level_4": 1}},
            {"level": 8, "proficiency_bonus": 3, "features": [{"name": "Wild Shape Improvement"}, {"name": "Ability Score Improvement"}], "spellcasting": {"cantrips_known": 4, "spell_slots_level_4": 2}},
            {"level": 9, "proficiency_bonus": 4, "features": [], "spellcasting": {"spell_slots_level_5": 1}},
            {"level": 10, "proficiency_bonus": 4, "features": [{"name": "Druid Circle Feature"}], "spellcasting": {"spell_slots_level_5": 2}},
            {"level": 11, "proficiency_bonus": 4, "features": [], "spellcasting": {"spell_slots_level_6": 1}},
            {"level": 12, "proficiency_bonus": 4, "features": [{"name": "Ability Score Improvement"}]},
            {"level": 13, "proficiency_bonus": 5, "features": [], "spellcasting": {"spell_slots_level_7": 1}},
            {"level": 14, "proficiency_bonus": 5, "features": [{"name": "Druid Circle Feature"}]},
            {"level": 15, "proficiency_bonus": 5, "features": [], "spellcasting": {"spell_slots_level_8": 1}},
            {"level": 16, "proficiency_bonus": 5, "features": [{"name": "Ability Score Improvement"}]},
            {"level": 17, "proficiency_bonus": 6, "features": [], "spellcasting": {"spell_slots_level_9": 1}},
            {"level": 18, "proficiency_bonus": 6, "features": [{"name": "Timeless Body"}, {"name": "Beast Spells"}]},
            {"level": 19, "proficiency_bonus": 6, "features": [{"name": "Ability Score Improvement"}]},
            {"level": 20, "proficiency_bonus": 6, "features": [{"name": "Archdruid"}]},
        ]
    },
    # --- Fighter ---
    {
        "class_data": {"name": "Fighter", "description": "A master of martial combat, skilled with a variety of weapons and armor.", "hit_die": 10},
        "levels": [
            {"level": 1, "proficiency_bonus": 2, "features": [{"name": "Fighting Style"}, {"name": "Second Wind"}]},
            {"level": 2, "proficiency_bonus": 2, "features": [{"name": "Action Surge (one use)"}]},
            {"level": 3, "proficiency_bonus": 2, "features": [{"name": "Martial Archetype"}]},
            {"level": 4, "proficiency_bonus": 2, "features": [{"name": "Ability Score Improvement"}]},
            {"level": 5, "proficiency_bonus": 3, "features": [{"name": "Extra Attack (1)"}]},
            {"level": 6, "proficiency_bonus": 3, "features": [{"name": "Ability Score Improvement"}]},
            {"level": 7, "proficiency_bonus": 3, "features": [{"name": "Martial Archetype feature"}]},
            {"level": 8, "proficiency_bonus": 3, "features": [{"name": "Ability Score Improvement"}]},
            {"level": 9, "proficiency_bonus": 4, "features": [{"name": "Indomitable (one use)"}]},
            {"level": 10, "proficiency_bonus": 4, "features": [{"name": "Martial Archetype feature"}]},
            {"level": 11, "proficiency_bonus": 4, "features": [{"name": "Extra Attack (2)"}]},
            {"level": 12, "proficiency_bonus": 4, "features": [{"name": "Ability Score Improvement"}]},
            {"level": 13, "proficiency_bonus": 5, "features": [{"name": "Indomitable (two uses)"}]},
            {"level": 14, "proficiency_bonus": 5, "features": [{"name": "Ability Score Improvement"}]},
            {"level": 15, "proficiency_bonus": 5, "features": [{"name": "Martial Archetype feature"}]},
            {"level": 16, "proficiency_bonus": 5, "features": [{"name": "Ability Score Improvement"}]},
            {"level": 17, "proficiency_bonus": 6, "features": [{"name": "Action Surge (two uses)"}, {"name": "Indomitable (three uses)"}]},
            {"level": 18, "proficiency_bonus": 6, "features": [{"name": "Martial Archetype feature"}]},
            {"level": 19, "proficiency_bonus": 6, "features": [{"name": "Ability Score Improvement"}]},
            {"level": 20, "proficiency_bonus": 6, "features": [{"name": "Extra Attack (3)"}]},
        ]
    },
    # --- Monk ---
    {
        "class_data": {"name": "Monk", "description": "A master of martial arts, harnessing the power of the body in pursuit of physical and spiritual perfection.", "hit_die": 8},
        "levels": [
            {"level": 1, "proficiency_bonus": 2, "features": [{"name": "Unarmored Defense"}, {"name": "Martial Arts (1d4)"}]},
            {"level": 2, "proficiency_bonus": 2, "features": [{"name": "Ki (2 points)"}, {"name": "Unarmored Movement (10 ft.)"}]},
            {"level": 3, "proficiency_bonus": 2, "features": [{"name": "Monastic Tradition"}, {"name": "Deflect Missiles"}]},
            {"level": 4, "proficiency_bonus": 2, "features": [{"name": "Ability Score Improvement"}, {"name": "Slow Fall"}]},
            {"level": 5, "proficiency_bonus": 3, "features": [{"name": "Extra Attack"}, {"name": "Stunning Strike"}, {"name": "Martial Arts (1d6)"}]},
            {"level": 6, "proficiency_bonus": 3, "features": [{"name": "Ki-Empowered Strikes"}, {"name": "Monastic Tradition feature"}, {"name": "Unarmored Movement (15 ft.)"}]},
            {"level": 7, "proficiency_bonus": 3, "features": [{"name": "Evasion"}, {"name": "Stillness of Mind"}]},
            {"level": 8, "proficiency_bonus": 3, "features": [{"name": "Ability Score Improvement"}]},
            {"level": 9, "proficiency_bonus": 4, "features": [{"name": "Unarmored Movement improvement"}]},
            {"level": 10, "proficiency_bonus": 4, "features": [{"name": "Purity of Body"}, {"name": "Unarmored Movement (20 ft.)"}]},
            {"level": 11, "proficiency_bonus": 4, "features": [{"name": "Monastic Tradition feature"}, {"name": "Martial Arts (1d8)"}]},
            {"level": 12, "proficiency_bonus": 4, "features": [{"name": "Ability Score Improvement"}]},
            {"level": 13, "proficiency_bonus": 5, "features": [{"name": "Tongue of the Sun and Moon"}]},
            {"level": 14, "proficiency_bonus": 5, "features": [{"name": "Diamond Soul"}, {"name": "Unarmored Movement (25 ft.)"}]},
            {"level": 15, "proficiency_bonus": 5, "features": [{"name": "Timeless Body"}]},
            {"level": 16, "proficiency_bonus": 5, "features": [{"name": "Ability Score Improvement"}]},
            {"level": 17, "proficiency_bonus": 6, "features": [{"name": "Monastic Tradition feature"}, {"name": "Martial Arts (1d10)"}]},
            {"level": 18, "proficiency_bonus": 6, "features": [{"name": "Empty Body"}, {"name": "Unarmored Movement (30 ft.)"}]},
            {"level": 19, "proficiency_bonus": 6, "features": [{"name": "Ability Score Improvement"}]},
            {"level": 20, "proficiency_bonus": 6, "features": [{"name": "Perfect Self"}]},
        ]
    },
    # --- Paladin ---
    {
        "class_data": {"name": "Paladin", "description": "A holy warrior bound to a sacred oath.", "hit_die": 10},
        "levels": [
            {"level": 1, "proficiency_bonus": 2, "features": [{"name": "Divine Sense"}, {"name": "Lay on Hands"}]},
            {"level": 2, "proficiency_bonus": 2, "features": [{"name": "Fighting Style"}, {"name": "Spellcasting"}, {"name": "Divine Smite"}], "spellcasting": {"spell_slots_level_1": 2}},
            {"level": 3, "proficiency_bonus": 2, "features": [{"name": "Divine Health"}, {"name": "Sacred Oath"}], "spellcasting": {"spell_slots_level_1": 3}},
            {"level": 4, "proficiency_bonus": 2, "features": [{"name": "Ability Score Improvement"}]},
            {"level": 5, "proficiency_bonus": 3, "features": [{"name": "Extra Attack"}], "spellcasting": {"spell_slots_level_2": 2}},
            {"level": 6, "proficiency_bonus": 3, "features": [{"name": "Aura of Protection"}]},
            {"level": 7, "proficiency_bonus": 3, "features": [{"name": "Sacred Oath feature"}], "spellcasting": {"spell_slots_level_2": 3}},
            {"level": 8, "proficiency_bonus": 3, "features": [{"name": "Ability Score Improvement"}]},
            {"level": 9, "proficiency_bonus": 4, "features": [], "spellcasting": {"spell_slots_level_3": 2}},
            {"level": 10, "proficiency_bonus": 4, "features": [{"name": "Aura of Courage"}]},
            {"level": 11, "proficiency_bonus": 4, "features": [{"name": "Improved Divine Smite"}], "spellcasting": {"spell_slots_level_3": 3}},
            {"level": 12, "proficiency_bonus": 4, "features": [{"name": "Ability Score Improvement"}]},
            {"level": 13, "proficiency_bonus": 5, "features": [], "spellcasting": {"spell_slots_level_4": 1}},
            {"level": 14, "proficiency_bonus": 5, "features": [{"name": "Cleansing Touch"}]},
            {"level": 15, "proficiency_bonus": 5, "features": [{"name": "Sacred Oath feature"}], "spellcasting": {"spell_slots_level_4": 2}},
            {"level": 16, "proficiency_bonus": 5, "features": [{"name": "Ability Score Improvement"}]},
            {"level": 17, "proficiency_bonus": 6, "features": [], "spellcasting": {"spell_slots_level_5": 1}},
            {"level": 18, "proficiency_bonus": 6, "features": [{"name": "Aura Improvements"}]},
            {"level": 19, "proficiency_bonus": 6, "features": [{"name": "Ability Score Improvement"}]},
            {"level": 20, "proficiency_bonus": 6, "features": [{"name": "Sacred Oath feature"}]},
        ]
    },
    # --- Ranger ---
    {
        "class_data": {"name": "Ranger", "description": "A warrior who uses martial prowess and nature magic to combat threats on the edges of civilization.", "hit_die": 10},
        "levels": [
            {"level": 1, "proficiency_bonus": 2, "features": [{"name": "Favored Enemy"}, {"name": "Natural Explorer"}]},
            {"level": 2, "proficiency_bonus": 2, "features": [{"name": "Fighting Style"}, {"name": "Spellcasting"}], "spellcasting": {"spells_known": 2, "spell_slots_level_1": 2}},
            {"level": 3, "proficiency_bonus": 2, "features": [{"name": "Ranger Archetype"}, {"name": "Primeval Awareness"}], "spellcasting": {"spells_known": 3, "spell_slots_level_1": 3}},
            {"level": 4, "proficiency_bonus": 2, "features": [{"name": "Ability Score Improvement"}]},
            {"level": 5, "proficiency_bonus": 3, "features": [{"name": "Extra Attack"}], "spellcasting": {"spells_known": 4, "spell_slots_level_2": 2}},
            {"level": 6, "proficiency_bonus": 3, "features": [{"name": "Favored Enemy and Natural Explorer improvements"}]},
            {"level": 7, "proficiency_bonus": 3, "features": [{"name": "Ranger Archetype feature"}], "spellcasting": {"spells_known": 5, "spell_slots_level_2": 3}},
            {"level": 8, "proficiency_bonus": 3, "features": [{"name": "Ability Score Improvement"}, {"name": "Land's Stride"}]},
            {"level": 9, "proficiency_bonus": 4, "features": [], "spellcasting": {"spells_known": 6, "spell_slots_level_3": 2}},
            {"level": 10, "proficiency_bonus": 4, "features": [{"name": "Natural Explorer improvement"}, {"name": "Hide in Plain Sight"}]},
            {"level": 11, "proficiency_bonus": 4, "features": [{"name": "Ranger Archetype feature"}], "spellcasting": {"spells_known": 7, "spell_slots_level_3": 3}},
            {"level": 12, "proficiency_bonus": 4, "features": [{"name": "Ability Score Improvement"}]},
            {"level": 13, "proficiency_bonus": 5, "features": [], "spellcasting": {"spells_known": 8, "spell_slots_level_4": 1}},
            {"level": 14, "proficiency_bonus": 5, "features": [{"name": "Favored Enemy improvement"}, {"name": "Vanish"}]},
            {"level": 15, "proficiency_bonus": 5, "features": [{"name": "Ranger Archetype feature"}], "spellcasting": {"spells_known": 9, "spell_slots_level_4": 2}},
            {"level": 16, "proficiency_bonus": 5, "features": [{"name": "Ability Score Improvement"}]},
            {"level": 17, "proficiency_bonus": 6, "features": [], "spellcasting": {"spells_known": 10, "spell_slots_level_5": 1}},
            {"level": 18, "proficiency_bonus": 6, "features": [{"name": "Feral Senses"}]},
            {"level": 19, "proficiency_bonus": 6, "features": [{"name": "Ability Score Improvement"}]},
            {"level": 20, "proficiency_bonus": 6, "features": [{"name": "Foe Slayer"}]},
        ]
    },
    # --- Rogue ---
    {
        "class_data": {"name": "Rogue", "description": "A scoundrel who uses stealth and trickery to overcome obstacles and enemies.", "hit_die": 8},
        "levels": [
            {"level": 1, "proficiency_bonus": 2, "features": [{"name": "Expertise"}, {"name": "Sneak Attack (1d6)"}, {"name": "Thieves' Cant"}]},
            {"level": 2, "proficiency_bonus": 2, "features": [{"name": "Cunning Action"}]},
            {"level": 3, "proficiency_bonus": 2, "features": [{"name": "Roguish Archetype"}, {"name": "Sneak Attack (2d6)"}]},
            {"level": 4, "proficiency_bonus": 2, "features": [{"name": "Ability Score Improvement"}]},
            {"level": 5, "proficiency_bonus": 3, "features": [{"name": "Uncanny Dodge"}, {"name": "Sneak Attack (3d6)"}]},
            {"level": 6, "proficiency_bonus": 3, "features": [{"name": "Expertise"}]},
            {"level": 7, "proficiency_bonus": 3, "features": [{"name": "Evasion"}, {"name": "Sneak Attack (4d6)"}]},
            {"level": 8, "proficiency_bonus": 3, "features": [{"name": "Ability Score Improvement"}]},
            {"level": 9, "proficiency_bonus": 4, "features": [{"name": "Roguish Archetype feature"}, {"name": "Sneak Attack (5d6)"}]},
            {"level": 10, "proficiency_bonus": 4, "features": [{"name": "Ability Score Improvement"}]},
            {"level": 11, "proficiency_bonus": 4, "features": [{"name": "Reliable Talent"}, {"name": "Sneak Attack (6d6)"}]},
            {"level": 12, "proficiency_bonus": 4, "features": [{"name": "Ability Score Improvement"}]},
            {"level": 13, "proficiency_bonus": 5, "features": [{"name": "Roguish Archetype feature"}, {"name": "Sneak Attack (7d6)"}]},
            {"level": 14, "proficiency_bonus": 5, "features": [{"name": "Blindsense"}]},
            {"level": 15, "proficiency_bonus": 5, "features": [{"name": "Slippery Mind"}, {"name": "Sneak Attack (8d6)"}]},
            {"level": 16, "proficiency_bonus": 5, "features": [{"name": "Ability Score Improvement"}]},
            {"level": 17, "proficiency_bonus": 6, "features": [{"name": "Roguish Archetype feature"}, {"name": "Sneak Attack (9d6)"}]},
            {"level": 18, "proficiency_bonus": 6, "features": [{"name": "Elusive"}]},
            {"level": 19, "proficiency_bonus": 6, "features": [{"name": "Ability Score Improvement"}, {"name": "Sneak Attack (10d6)"}]},
            {"level": 20, "proficiency_bonus": 6, "features": [{"name": "Stroke of Luck"}]},
        ]
    },
    # --- Sorcerer ---
    {
        "class_data": {"name": "Sorcerer", "description": "A spellcaster who draws on inherent magic from a gift or bloodline.", "hit_die": 6},
        "levels": [
            {"level": 1, "proficiency_bonus": 2, "features": [{"name": "Spellcasting"}, {"name": "Sorcerous Origin"}], "spellcasting": {"cantrips_known": 4, "spells_known": 2, "spell_slots_level_1": 2}},
            {"level": 2, "proficiency_bonus": 2, "features": [{"name": "Font of Magic"}], "spellcasting": {"spells_known": 3, "spell_slots_level_1": 3}},
            {"level": 3, "proficiency_bonus": 2, "features": [{"name": "Metamagic"}], "spellcasting": {"spells_known": 4, "spell_slots_level_2": 2}},
            {"level": 4, "proficiency_bonus": 2, "features": [{"name": "Ability Score Improvement"}], "spellcasting": {"cantrips_known": 5, "spells_known": 5, "spell_slots_level_2": 3}},
            {"level": 5, "proficiency_bonus": 3, "features": [], "spellcasting": {"spells_known": 6, "spell_slots_level_3": 2}},
            {"level": 6, "proficiency_bonus": 3, "features": [{"name": "Sorcerous Origin feature"}], "spellcasting": {"spells_known": 7, "spell_slots_level_3": 3}},
            {"level": 7, "proficiency_bonus": 3, "features": [], "spellcasting": {"spells_known": 8, "spell_slots_level_4": 1}},
            {"level": 8, "proficiency_bonus": 3, "features": [{"name": "Ability Score Improvement"}], "spellcasting": {"spells_known": 9, "spell_slots_level_4": 2}},
            {"level": 9, "proficiency_bonus": 4, "features": [], "spellcasting": {"spells_known": 10, "spell_slots_level_5": 1}},
            {"level": 10, "proficiency_bonus": 4, "features": [{"name": "Metamagic"}], "spellcasting": {"cantrips_known": 6, "spells_known": 11, "spell_slots_level_5": 2}},
            {"level": 11, "proficiency_bonus": 4, "features": [], "spellcasting": {"spells_known": 12, "spell_slots_level_6": 1}},
            {"level": 12, "proficiency_bonus": 4, "features": [{"name": "Ability Score Improvement"}]},
            {"level": 13, "proficiency_bonus": 5, "features": [], "spellcasting": {"spells_known": 13, "spell_slots_level_7": 1}},
            {"level": 14, "proficiency_bonus": 5, "features": [{"name": "Sorcerous Origin feature"}]},
            {"level": 15, "proficiency_bonus": 5, "features": [], "spellcasting": {"spells_known": 14, "spell_slots_level_8": 1}},
            {"level": 16, "proficiency_bonus": 5, "features": [{"name": "Ability Score Improvement"}]},
            {"level": 17, "proficiency_bonus": 6, "features": [{"name": "Metamagic"}], "spellcasting": {"spells_known": 15, "spell_slots_level_9": 1}},
            {"level": 18, "proficiency_bonus": 6, "features": [{"name": "Sorcerous Origin feature"}], "spellcasting": {"spell_slots_level_5": 3}},
            {"level": 19, "proficiency_bonus": 6, "features": [{"name": "Ability Score Improvement"}], "spellcasting": {"spell_slots_level_6": 2}},
            {"level": 20, "proficiency_bonus": 6, "features": [{"name": "Sorcerous Restoration"}], "spellcasting": {"spell_slots_level_7": 2}},
        ]
    },
    # --- Warlock ---
    {
        "class_data": {"name": "Warlock", "description": "A wielder of magic that is derived from a bargain with an extraplanar entity.", "hit_die": 8},
        "levels": [
            {"level": 1, "proficiency_bonus": 2, "features": [{"name": "Otherworldly Patron"}, {"name": "Pact Magic"}], "spellcasting": {"cantrips_known": 2, "spells_known": 2, "spell_slots": 1, "slot_level": 1}},
            {"level": 2, "proficiency_bonus": 2, "features": [{"name": "Eldritch Invocations"}], "spellcasting": {"spells_known": 3, "spell_slots": 2}},
            {"level": 3, "proficiency_bonus": 2, "features": [{"name": "Pact Boon"}], "spellcasting": {"spells_known": 4, "slot_level": 2}},
            {"level": 4, "proficiency_bonus": 2, "features": [{"name": "Ability Score Improvement"}], "spellcasting": {"cantrips_known": 3, "spells_known": 5}},
            {"level": 5, "proficiency_bonus": 3, "features": [], "spellcasting": {"spells_known": 6, "slot_level": 3}},
            {"level": 6, "proficiency_bonus": 3, "features": [{"name": "Otherworldly Patron feature"}]},
            {"level": 7, "proficiency_bonus": 3, "features": [], "spellcasting": {"spells_known": 8, "slot_level": 4}},
            {"level": 8, "proficiency_bonus": 3, "features": [{"name": "Ability Score Improvement"}]},
            {"level": 9, "proficiency_bonus": 4, "features": [], "spellcasting": {"spells_known": 10, "slot_level": 5}},
            {"level": 10, "proficiency_bonus": 4, "features": [{"name": "Otherworldly Patron feature"}], "spellcasting": {"cantrips_known": 4}},
            {"level": 11, "proficiency_bonus": 4, "features": [{"name": "Mystic Arcanum (6th level)"}], "spellcasting": {"spells_known": 11, "spell_slots": 3}},
            {"level": 12, "proficiency_bonus": 4, "features": [{"name": "Ability Score Improvement"}]},
            {"level": 13, "proficiency_bonus": 5, "features": [{"name": "Mystic Arcanum (7th level)"}], "spellcasting": {"spells_known": 12}},
            {"level": 14, "proficiency_bonus": 5, "features": [{"name": "Otherworldly Patron feature"}]},
            {"level": 15, "proficiency_bonus": 5, "features": [{"name": "Mystic Arcanum (8th level)"}], "spellcasting": {"spells_known": 13}},
            {"level": 16, "proficiency_bonus": 5, "features": [{"name": "Ability Score Improvement"}]},
            {"level": 17, "proficiency_bonus": 6, "features": [{"name": "Mystic Arcanum (9th level)"}], "spellcasting": {"spells_known": 14, "spell_slots": 4}},
            {"level": 18, "proficiency_bonus": 6, "features": []},
            {"level": 19, "proficiency_bonus": 6, "features": [{"name": "Ability Score Improvement"}]},
            {"level": 20, "proficiency_bonus": 6, "features": [{"name": "Eldritch Master"}]},
        ]
    },
    # --- Wizard ---
    {
        "class_data": {"name": "Wizard", "description": "A scholarly magic-user capable of manipulating the structures of reality.", "hit_die": 6},
        "levels": [
            {"level": 1, "proficiency_bonus": 2, "features": [{"name": "Spellcasting"}, {"name": "Arcane Recovery"}], "spellcasting": {"cantrips_known": 3, "spell_slots_level_1": 2}},
            {"level": 2, "proficiency_bonus": 2, "features": [{"name": "Arcane Tradition"}], "spellcasting": {"spell_slots_level_1": 3}},
            {"level": 3, "proficiency_bonus": 2, "features": [], "spellcasting": {"spell_slots_level_2": 2}},
            {"level": 4, "proficiency_bonus": 2, "features": [{"name": "Ability Score Improvement"}], "spellcasting": {"cantrips_known": 4, "spell_slots_level_2": 3}},
            {"level": 5, "proficiency_bonus": 3, "features": [], "spellcasting": {"spell_slots_level_3": 2}},
            {"level": 6, "proficiency_bonus": 3, "features": [{"name": "Arcane Tradition feature"}], "spellcasting": {"spell_slots_level_3": 3}},
            {"level": 7, "proficiency_bonus": 3, "features": [], "spellcasting": {"spell_slots_level_4": 1}},
            {"level": 8, "proficiency_bonus": 3, "features": [{"name": "Ability Score Improvement"}], "spellcasting": {"spell_slots_level_4": 2}},
            {"level": 9, "proficiency_bonus": 4, "features": [], "spellcasting": {"spell_slots_level_5": 1}},
            {"level": 10, "proficiency_bonus": 4, "features": [{"name": "Arcane Tradition feature"}], "spellcasting": {"cantrips_known": 5, "spell_slots_level_5": 2}},
            {"level": 11, "proficiency_bonus": 4, "features": [], "spellcasting": {"spell_slots_level_6": 1}},
            {"level": 12, "proficiency_bonus": 4, "features": [{"name": "Ability Score Improvement"}]},
            {"level": 13, "proficiency_bonus": 5, "features": [], "spellcasting": {"spell_slots_level_7": 1}},
            {"level": 14, "proficiency_bonus": 5, "features": [{"name": "Arcane Tradition feature"}]},
            {"level": 15, "proficiency_bonus": 5, "features": [], "spellcasting": {"spell_slots_level_8": 1}},
            {"level": 16, "proficiency_bonus": 5, "features": [{"name": "Ability Score Improvement"}]},
            {"level": 17, "proficiency_bonus": 6, "features": [], "spellcasting": {"spell_slots_level_9": 1}},
            {"level": 18, "proficiency_bonus": 6, "features": [{"name": "Spell Mastery"}]},
            {"level": 19, "proficiency_bonus": 6, "features": [{"name": "Ability Score Improvement"}]},
            {"level": 20, "proficiency_bonus": 6, "features": [{"name": "Signature Spells"}]},
        ]
    }
]