# Path: api/app/game_data/items_data.py
from app.schemas.item import ItemCreate as ItemCreateSchema
from app.models.item import ItemTypeEnum

# This list contains a comprehensive list of items from the D&D 5.1 Systems Reference Document (SRD).
PREDEFINED_ITEMS = [
    # --- Adventuring Gear ---
    ItemCreateSchema(name="Abacus", item_type=ItemTypeEnum.ADVENTURING_GEAR, weight=2.0, cost_gp=2.0),
    ItemCreateSchema(name="Acid (vial)", item_type=ItemTypeEnum.ADVENTURING_GEAR, weight=1.0, cost_gp=25.0),
    ItemCreateSchema(name="Alchemist's Fire (flask)", item_type=ItemTypeEnum.ADVENTURING_GEAR, weight=1.0, cost_gp=50.0),
    ItemCreateSchema(name="Ammunition, Arrows (20)", item_type=ItemTypeEnum.ADVENTURING_GEAR, weight=1.0, cost_gp=1.0),
    ItemCreateSchema(name="Ammunition, Blowgun needles (50)", item_type=ItemTypeEnum.ADVENTURING_GEAR, weight=1.0, cost_gp=1.0),
    ItemCreateSchema(name="Ammunition, Crossbow bolts (20)", item_type=ItemTypeEnum.ADVENTURING_GEAR, weight=1.5, cost_gp=1.0),
    ItemCreateSchema(name="Ammunition, Sling bullets (20)", item_type=ItemTypeEnum.ADVENTURING_GEAR, weight=1.5, cost_gp=0.04),
    ItemCreateSchema(name="Antitoxin (vial)", item_type=ItemTypeEnum.ADVENTURING_GEAR, weight=0, cost_gp=50.0),
    ItemCreateSchema(name="Backpack", item_type=ItemTypeEnum.ADVENTURING_GEAR, weight=5.0, cost_gp=2.0, properties={"capacity_lbs": 30, "description": "Holds 1 cubic foot or 30 pounds of gear."}),
    ItemCreateSchema(name="Ball Bearings (bag of 1,000)", item_type=ItemTypeEnum.ADVENTURING_GEAR, weight=2.0, cost_gp=1.0),
    ItemCreateSchema(name="Barrel", item_type=ItemTypeEnum.ADVENTURING_GEAR, weight=70.0, cost_gp=2.0),
    ItemCreateSchema(name="Basket", item_type=ItemTypeEnum.ADVENTURING_GEAR, weight=2.0, cost_gp=0.4),
    ItemCreateSchema(name="Bedroll", item_type=ItemTypeEnum.ADVENTURING_GEAR, weight=7.0, cost_gp=1.0),
    ItemCreateSchema(name="Bell", item_type=ItemTypeEnum.ADVENTURING_GEAR, weight=0, cost_gp=1.0),
    ItemCreateSchema(name="Blanket", item_type=ItemTypeEnum.ADVENTURING_GEAR, weight=3.0, cost_gp=0.5),
    ItemCreateSchema(name="Block and tackle", item_type=ItemTypeEnum.ADVENTURING_GEAR, weight=5.0, cost_gp=1.0),
    ItemCreateSchema(name="Book", item_type=ItemTypeEnum.ADVENTURING_GEAR, weight=5.0, cost_gp=25.0),
    ItemCreateSchema(name="Bottle, glass", item_type=ItemTypeEnum.ADVENTURING_GEAR, weight=2.0, cost_gp=2.0),
    ItemCreateSchema(name="Bucket", item_type=ItemTypeEnum.ADVENTURING_GEAR, weight=2.0, cost_gp=0.05),
    ItemCreateSchema(name="Caltrops (bag of 20)", item_type=ItemTypeEnum.ADVENTURING_GEAR, weight=2.0, cost_gp=1.0),
    ItemCreateSchema(name="Candle", item_type=ItemTypeEnum.ADVENTURING_GEAR, weight=0, cost_gp=0.01),
    ItemCreateSchema(name="Case, Crossbow bolt", item_type=ItemTypeEnum.ADVENTURING_GEAR, weight=1.0, cost_gp=1.0),
    ItemCreateSchema(name="Case, Map or scroll", item_type=ItemTypeEnum.ADVENTURING_GEAR, weight=1.0, cost_gp=1.0),
    ItemCreateSchema(name="Chain (10 feet)", item_type=ItemTypeEnum.ADVENTURING_GEAR, weight=10.0, cost_gp=5.0),
    ItemCreateSchema(name="Chalk (1 piece)", item_type=ItemTypeEnum.ADVENTURING_GEAR, weight=0, cost_gp=0.01),
    ItemCreateSchema(name="Chest", item_type=ItemTypeEnum.ADVENTURING_GEAR, weight=25.0, cost_gp=5.0),
    ItemCreateSchema(name="Clothes, Common", item_type=ItemTypeEnum.ADVENTURING_GEAR, weight=3.0, cost_gp=0.5),
    ItemCreateSchema(name="Clothes, Costume", item_type=ItemTypeEnum.ADVENTURING_GEAR, weight=4.0, cost_gp=5.0),
    ItemCreateSchema(name="Clothes, Fine", item_type=ItemTypeEnum.ADVENTURING_GEAR, weight=6.0, cost_gp=15.0),
    ItemCreateSchema(name="Clothes, Traveler's", item_type=ItemTypeEnum.ADVENTURING_GEAR, weight=4.0, cost_gp=2.0),
    ItemCreateSchema(name="Component pouch", item_type=ItemTypeEnum.ADVENTURING_GEAR, weight=2.0, cost_gp=25.0),
    ItemCreateSchema(name="Crowbar", item_type=ItemTypeEnum.ADVENTURING_GEAR, weight=5.0, cost_gp=2.0),
    ItemCreateSchema(name="Flask or tankard", item_type=ItemTypeEnum.ADVENTURING_GEAR, weight=1.0, cost_gp=0.02),
    ItemCreateSchema(name="Grappling hook", item_type=ItemTypeEnum.ADVENTURING_GEAR, weight=4.0, cost_gp=2.0),
    ItemCreateSchema(name="Hammer", item_type=ItemTypeEnum.ADVENTURING_GEAR, weight=3.0, cost_gp=1.0),
    ItemCreateSchema(name="Hammer, Sledge", item_type=ItemTypeEnum.ADVENTURING_GEAR, weight=10.0, cost_gp=2.0),
    ItemCreateSchema(name="Holy water (flask)", item_type=ItemTypeEnum.ADVENTURING_GEAR, weight=1.0, cost_gp=25.0),
    ItemCreateSchema(name="Hourglass", item_type=ItemTypeEnum.ADVENTURING_GEAR, weight=1.0, cost_gp=25.0),
    ItemCreateSchema(name="Hunting trap", item_type=ItemTypeEnum.ADVENTURING_GEAR, weight=25.0, cost_gp=5.0),
    ItemCreateSchema(name="Ink (1 ounce bottle)", item_type=ItemTypeEnum.ADVENTURING_GEAR, weight=0, cost_gp=10.0),
    ItemCreateSchema(name="Ink pen", item_type=ItemTypeEnum.ADVENTURING_GEAR, weight=0, cost_gp=0.02),
    ItemCreateSchema(name="Jug or pitcher", item_type=ItemTypeEnum.ADVENTURING_GEAR, weight=4.0, cost_gp=0.02),
    ItemCreateSchema(name="Ladder (10-foot)", item_type=ItemTypeEnum.ADVENTURING_GEAR, weight=25.0, cost_gp=0.1),
    ItemCreateSchema(name="Lamp", item_type=ItemTypeEnum.ADVENTURING_GEAR, weight=1.0, cost_gp=0.5),
    ItemCreateSchema(name="Lantern, Bullseye", item_type=ItemTypeEnum.ADVENTURING_GEAR, weight=2.0, cost_gp=10.0),
    ItemCreateSchema(name="Lantern, Hooded", item_type=ItemTypeEnum.ADVENTURING_GEAR, weight=2.0, cost_gp=5.0),
    ItemCreateSchema(name="Lock", item_type=ItemTypeEnum.ADVENTURING_GEAR, weight=1.0, cost_gp=10.0),
    ItemCreateSchema(name="Magnifying glass", item_type=ItemTypeEnum.ADVENTURING_GEAR, weight=0, cost_gp=100.0),
    ItemCreateSchema(name="Manacles", item_type=ItemTypeEnum.ADVENTURING_GEAR, weight=6.0, cost_gp=2.0),
    ItemCreateSchema(name="Mess Kit", item_type=ItemTypeEnum.ADVENTURING_GEAR, weight=1.0, cost_gp=0.2),
    ItemCreateSchema(name="Mirror, steel", item_type=ItemTypeEnum.ADVENTURING_GEAR, weight=0.5, cost_gp=5.0),
    ItemCreateSchema(name="Oil (flask)", item_type=ItemTypeEnum.ADVENTURING_GEAR, weight=1.0, cost_gp=0.1),
    ItemCreateSchema(name="Paper (one sheet)", item_type=ItemTypeEnum.ADVENTURING_GEAR, weight=0, cost_gp=0.2),
    ItemCreateSchema(name="Parchment (one sheet)", item_type=ItemTypeEnum.ADVENTURING_GEAR, weight=0, cost_gp=0.1),
    ItemCreateSchema(name="Perfume (vial)", item_type=ItemTypeEnum.ADVENTURING_GEAR, weight=0, cost_gp=5.0),
    ItemCreateSchema(name="Pick, miner's", item_type=ItemTypeEnum.ADVENTURING_GEAR, weight=10.0, cost_gp=2.0),
    ItemCreateSchema(name="Piton", item_type=ItemTypeEnum.ADVENTURING_GEAR, weight=0.25, cost_gp=0.05),
    ItemCreateSchema(name="Poison, basic (vial)", item_type=ItemTypeEnum.ADVENTURING_GEAR, weight=0, cost_gp=100.0),
    ItemCreateSchema(name="Pole (10-foot)", item_type=ItemTypeEnum.ADVENTURING_GEAR, weight=7.0, cost_gp=0.05),
    ItemCreateSchema(name="Pot, iron", item_type=ItemTypeEnum.ADVENTURING_GEAR, weight=10.0, cost_gp=2.0),
    ItemCreateSchema(name="Pouch", item_type=ItemTypeEnum.ADVENTURING_GEAR, weight=1.0, cost_gp=0.5),
    ItemCreateSchema(name="Quiver", item_type=ItemTypeEnum.ADVENTURING_GEAR, weight=1.0, cost_gp=1.0),
    ItemCreateSchema(name="Ram, portable", item_type=ItemTypeEnum.ADVENTURING_GEAR, weight=35.0, cost_gp=4.0),
    ItemCreateSchema(name="Rations (1 day)", item_type=ItemTypeEnum.ADVENTURING_GEAR, weight=2.0, cost_gp=0.5),
    ItemCreateSchema(name="Rope, Hempen (50 feet)", item_type=ItemTypeEnum.ADVENTURING_GEAR, weight=10.0, cost_gp=1.0),
    ItemCreateSchema(name="Rope, Silk (50 feet)", item_type=ItemTypeEnum.ADVENTURING_GEAR, weight=5.0, cost_gp=10.0),
    ItemCreateSchema(name="Sack", item_type=ItemTypeEnum.ADVENTURING_GEAR, weight=0.5, cost_gp=0.01),
    ItemCreateSchema(name="Scale, merchant's", item_type=ItemTypeEnum.ADVENTURING_GEAR, weight=3.0, cost_gp=5.0),
    ItemCreateSchema(name="Sealing wax", item_type=ItemTypeEnum.ADVENTURING_GEAR, weight=0, cost_gp=0.5),
    ItemCreateSchema(name="Shovel", item_type=ItemTypeEnum.ADVENTURING_GEAR, weight=5.0, cost_gp=2.0),
    ItemCreateSchema(name="Signal whistle", item_type=ItemTypeEnum.ADVENTURING_GEAR, weight=0, cost_gp=0.05),
    ItemCreateSchema(name="Signet ring", item_type=ItemTypeEnum.ADVENTURING_GEAR, weight=0, cost_gp=5.0),
    ItemCreateSchema(name="Soap", item_type=ItemTypeEnum.ADVENTURING_GEAR, weight=0, cost_gp=0.02),
    ItemCreateSchema(name="Spellbook", item_type=ItemTypeEnum.ADVENTURING_GEAR, weight=3.0, cost_gp=50.0),
    ItemCreateSchema(name="Spikes, iron (10)", item_type=ItemTypeEnum.ADVENTURING_GEAR, weight=5.0, cost_gp=1.0),
    ItemCreateSchema(name="Spyglass", item_type=ItemTypeEnum.ADVENTURING_GEAR, weight=1.0, cost_gp=1000.0),
    ItemCreateSchema(name="Tent, two-person", item_type=ItemTypeEnum.ADVENTURING_GEAR, weight=20.0, cost_gp=2.0),
    ItemCreateSchema(name="Tinderbox", item_type=ItemTypeEnum.ADVENTURING_GEAR, weight=1.0, cost_gp=0.5, properties={"description": "For lighting fires."}),
    ItemCreateSchema(name="Torch", item_type=ItemTypeEnum.ADVENTURING_GEAR, weight=1.0, cost_gp=0.01, properties={"duration_hours": 1, "light_radius_ft": "20 bright, 20 dim"}),
    ItemCreateSchema(name="Vial", item_type=ItemTypeEnum.ADVENTURING_GEAR, weight=0, cost_gp=1.0),
    ItemCreateSchema(name="Waterskin", item_type=ItemTypeEnum.ADVENTURING_GEAR, weight=5.0, cost_gp=0.2, properties={"capacity_gallons": 0.5, "full_weight_lbs": 5}),
    ItemCreateSchema(name="Whetstone", item_type=ItemTypeEnum.ADVENTURING_GEAR, weight=1.0, cost_gp=0.01),

    # --- Tools ---
    ItemCreateSchema(name="Alchemist's supplies", item_type=ItemTypeEnum.TOOL, weight=8.0, cost_gp=50.0),
    ItemCreateSchema(name="Brewer's supplies", item_type=ItemTypeEnum.TOOL, weight=9.0, cost_gp=20.0),
    ItemCreateSchema(name="Calligrapher's supplies", item_type=ItemTypeEnum.TOOL, weight=5.0, cost_gp=10.0),
    ItemCreateSchema(name="Carpenter's tools", item_type=ItemTypeEnum.TOOL, weight=6.0, cost_gp=8.0),
    ItemCreateSchema(name="Cartographer's tools", item_type=ItemTypeEnum.TOOL, weight=6.0, cost_gp=15.0),
    ItemCreateSchema(name="Cobbler's tools", item_type=ItemTypeEnum.TOOL, weight=5.0, cost_gp=5.0),
    ItemCreateSchema(name="Cook's utensils", item_type=ItemTypeEnum.TOOL, weight=8.0, cost_gp=1.0),
    ItemCreateSchema(name="Glassblower's tools", item_type=ItemTypeEnum.TOOL, weight=5.0, cost_gp=30.0),
    ItemCreateSchema(name="Jeweler's tools", item_type=ItemTypeEnum.TOOL, weight=2.0, cost_gp=25.0),
    ItemCreateSchema(name="Leatherworker's tools", item_type=ItemTypeEnum.TOOL, weight=5.0, cost_gp=5.0),
    ItemCreateSchema(name="Mason's tools", item_type=ItemTypeEnum.TOOL, weight=10.0, cost_gp=10.0),
    ItemCreateSchema(name="Painter's supplies", item_type=ItemTypeEnum.TOOL, weight=5.0, cost_gp=10.0),
    ItemCreateSchema(name="Potter's tools", item_type=ItemTypeEnum.TOOL, weight=3.0, cost_gp=10.0),
    ItemCreateSchema(name="Smith's tools", item_type=ItemTypeEnum.TOOL, weight=8.0, cost_gp=20.0),
    ItemCreateSchema(name="Tinker's tools", item_type=ItemTypeEnum.TOOL, weight=10.0, cost_gp=50.0),
    ItemCreateSchema(name="Weaver's tools", item_type=ItemTypeEnum.TOOL, weight=5.0, cost_gp=1.0),
    ItemCreateSchema(name="Woodcarver's tools", item_type=ItemTypeEnum.TOOL, weight=5.0, cost_gp=1.0),
    ItemCreateSchema(name="Disguise kit", item_type=ItemTypeEnum.TOOL, weight=3.0, cost_gp=25.0),
    ItemCreateSchema(name="Forgery kit", item_type=ItemTypeEnum.TOOL, weight=5.0, cost_gp=15.0),
    ItemCreateSchema(name="Dice set", item_type=ItemTypeEnum.TOOL, weight=0, cost_gp=0.1),
    ItemCreateSchema(name="Playing card set", item_type=ItemTypeEnum.TOOL, weight=0, cost_gp=0.5),
    ItemCreateSchema(name="Herbalism kit", item_type=ItemTypeEnum.TOOL, weight=3.0, cost_gp=5.0),
    ItemCreateSchema(name="Bagpipes", item_type=ItemTypeEnum.TOOL, weight=6.0, cost_gp=30.0),
    ItemCreateSchema(name="Drum", item_type=ItemTypeEnum.TOOL, weight=3.0, cost_gp=6.0),
    ItemCreateSchema(name="Dulcimer", item_type=ItemTypeEnum.TOOL, weight=10.0, cost_gp=25.0),
    ItemCreateSchema(name="Flute", item_type=ItemTypeEnum.TOOL, weight=1.0, cost_gp=2.0),
    ItemCreateSchema(name="Lute", item_type=ItemTypeEnum.TOOL, weight=2.0, cost_gp=35.0),
    ItemCreateSchema(name="Lyre", item_type=ItemTypeEnum.TOOL, weight=2.0, cost_gp=30.0),
    ItemCreateSchema(name="Horn", item_type=ItemTypeEnum.TOOL, weight=2.0, cost_gp=3.0),
    ItemCreateSchema(name="Pan flute", item_type=ItemTypeEnum.TOOL, weight=2.0, cost_gp=12.0),
    ItemCreateSchema(name="Shawm", item_type=ItemTypeEnum.TOOL, weight=1.0, cost_gp=2.0),
    ItemCreateSchema(name="Viol", item_type=ItemTypeEnum.TOOL, weight=1.0, cost_gp=30.0),
    ItemCreateSchema(name="Navigator's tools", item_type=ItemTypeEnum.TOOL, weight=2.0, cost_gp=25.0),
    ItemCreateSchema(name="Poisoner's kit", item_type=ItemTypeEnum.TOOL, weight=2.0, cost_gp=50.0),
    ItemCreateSchema(name="Thieves' Tools", item_type=ItemTypeEnum.TOOL, weight=1.0, cost_gp=25.0, properties={"use": "Disarm traps, open locks"}),

    # --- Armor & Shields ---
    ItemCreateSchema(name="Padded Armor", item_type=ItemTypeEnum.ARMOR, weight=8.0, cost_gp=5.0, properties={"ac_base": 11, "armor_type": "light", "dex_bonus": True, "stealth_disadvantage": True}),
    ItemCreateSchema(name="Leather Armor", item_type=ItemTypeEnum.ARMOR, weight=10.0, cost_gp=10.0, properties={"ac_base": 11, "armor_type": "light", "dex_bonus": True, "stealth_disadvantage": False}),
    ItemCreateSchema(name="Studded Leather", item_type=ItemTypeEnum.ARMOR, weight=13.0, cost_gp=45.0, properties={"ac_base": 12, "armor_type": "light", "dex_bonus": True, "stealth_disadvantage": False}),
    ItemCreateSchema(name="Hide Armor", item_type=ItemTypeEnum.ARMOR, weight=12.0, cost_gp=10.0, properties={"ac_base": 12, "armor_type": "medium", "dex_bonus": True, "dex_bonus_max": 2, "stealth_disadvantage": False}),
    ItemCreateSchema(name="Chain Shirt", item_type=ItemTypeEnum.ARMOR, weight=20.0, cost_gp=50.0, properties={"ac_base": 13, "armor_type": "medium", "dex_bonus": True, "dex_bonus_max": 2, "stealth_disadvantage": False}),
    ItemCreateSchema(name="Scale Mail", item_type=ItemTypeEnum.ARMOR, weight=45.0, cost_gp=50.0, properties={"ac_base": 14, "armor_type": "medium", "dex_bonus": True, "dex_bonus_max": 2, "stealth_disadvantage": True}),
    ItemCreateSchema(name="Breastplate", item_type=ItemTypeEnum.ARMOR, weight=20.0, cost_gp=400.0, properties={"ac_base": 14, "armor_type": "medium", "dex_bonus": True, "dex_bonus_max": 2, "stealth_disadvantage": False}),
    ItemCreateSchema(name="Half Plate Armor", item_type=ItemTypeEnum.ARMOR, weight=40.0, cost_gp=750.0, properties={"ac_base": 15, "armor_type": "medium", "dex_bonus": True, "dex_bonus_max": 2, "stealth_disadvantage": True}),
    ItemCreateSchema(name="Ring Mail", item_type=ItemTypeEnum.ARMOR, weight=40.0, cost_gp=30.0, properties={"ac_base": 14, "armor_type": "heavy", "dex_bonus": False, "stealth_disadvantage": True}),
    ItemCreateSchema(name="Chain Mail", item_type=ItemTypeEnum.ARMOR, weight=55.0, cost_gp=75.0, properties={"ac_base": 16, "armor_type": "heavy", "dex_bonus": False, "stealth_disadvantage": True, "strength_required": 13}),
    ItemCreateSchema(name="Splint Armor", item_type=ItemTypeEnum.ARMOR, weight=60.0, cost_gp=200.0, properties={"ac_base": 17, "armor_type": "heavy", "dex_bonus": False, "stealth_disadvantage": True, "strength_required": 15}),
    ItemCreateSchema(name="Plate Armor", item_type=ItemTypeEnum.ARMOR, weight=65.0, cost_gp=1500.0, properties={"ac_base": 18, "armor_type": "heavy", "dex_bonus": False, "stealth_disadvantage": True, "strength_required": 15}),
    ItemCreateSchema(name="Shield", item_type=ItemTypeEnum.SHIELD, weight=6.0, cost_gp=10.0, properties={"ac_bonus": 2}),
    
    # --- Weapons ---
    ItemCreateSchema(name="Club", item_type=ItemTypeEnum.WEAPON, weight=2.0, cost_gp=0.1, properties={"damage": "1d4 bludgeoning", "type": "simple melee", "properties": ["light"]}),
    ItemCreateSchema(name="Dagger", item_type=ItemTypeEnum.WEAPON, weight=1.0, cost_gp=2.0, properties={"damage": "1d4 piercing", "type": "simple melee", "properties": ["finesse", "light", "thrown (range 20/60)"]}),
    ItemCreateSchema(name="Greatclub", item_type=ItemTypeEnum.WEAPON, weight=10.0, cost_gp=0.2, properties={"damage": "1d8 bludgeoning", "type": "simple melee", "properties": ["two-handed"]}),
    ItemCreateSchema(name="Handaxe", item_type=ItemTypeEnum.WEAPON, weight=2.0, cost_gp=5.0, properties={"damage": "1d6 slashing", "type": "simple melee", "properties": ["light", "thrown (range 20/60)"]}),
    ItemCreateSchema(name="Javelin", item_type=ItemTypeEnum.WEAPON, weight=2.0, cost_gp=0.5, properties={"damage": "1d6 piercing", "type": "simple melee", "properties": ["thrown (range 30/120)"]}),
    ItemCreateSchema(name="Light Hammer", item_type=ItemTypeEnum.WEAPON, weight=2.0, cost_gp=2.0, properties={"damage": "1d4 bludgeoning", "type": "simple melee", "properties": ["light", "thrown (range 20/60)"]}),
    ItemCreateSchema(name="Mace", item_type=ItemTypeEnum.WEAPON, weight=4.0, cost_gp=5.0, properties={"damage": "1d6 bludgeoning", "type": "simple melee", "properties": []}),
    ItemCreateSchema(name="Quarterstaff", item_type=ItemTypeEnum.WEAPON, weight=4.0, cost_gp=0.2, properties={"damage": "1d6 bludgeoning", "type": "simple melee", "properties": ["versatile (1d8)"]}),
    ItemCreateSchema(name="Sickle", item_type=ItemTypeEnum.WEAPON, weight=2.0, cost_gp=1.0, properties={"damage": "1d4 slashing", "type": "simple melee", "properties": ["light"]}),
    ItemCreateSchema(name="Spear", item_type=ItemTypeEnum.WEAPON, weight=3.0, cost_gp=1.0, properties={"damage": "1d6 piercing", "type": "simple melee", "properties": ["thrown (range 20/60)", "versatile (1d8)"]}),
    ItemCreateSchema(name="Light Crossbow", item_type=ItemTypeEnum.WEAPON, weight=5.0, cost_gp=25.0, properties={"damage": "1d8 piercing", "type": "simple ranged", "properties": ["ammunition (range 80/320)", "loading", "two-handed"]}),
    ItemCreateSchema(name="Dart", item_type=ItemTypeEnum.WEAPON, weight=0.25, cost_gp=0.05, properties={"damage": "1d4 piercing", "type": "simple ranged", "properties": ["finesse", "thrown (range 20/60)"]}),
    ItemCreateSchema(name="Shortbow", item_type=ItemTypeEnum.WEAPON, weight=2.0, cost_gp=25.0, properties={"damage": "1d6 piercing", "type": "simple ranged", "properties": ["ammunition (range 80/320)", "two-handed"]}),
    ItemCreateSchema(name="Sling", item_type=ItemTypeEnum.WEAPON, weight=0, cost_gp=0.1, properties={"damage": "1d4 bludgeoning", "type": "simple ranged", "properties": ["ammunition (range 30/120)"]}),
    ItemCreateSchema(name="Battleaxe", item_type=ItemTypeEnum.WEAPON, weight=4.0, cost_gp=10.0, properties={"damage": "1d8 slashing", "type": "martial melee", "properties": ["versatile (1d10)"]}),
    ItemCreateSchema(name="Flail", item_type=ItemTypeEnum.WEAPON, weight=2.0, cost_gp=10.0, properties={"damage": "1d8 bludgeoning", "type": "martial melee", "properties": []}),
    ItemCreateSchema(name="Glaive", item_type=ItemTypeEnum.WEAPON, weight=6.0, cost_gp=20.0, properties={"damage": "1d10 slashing", "type": "martial melee", "properties": ["heavy", "reach", "two-handed"]}),
    ItemCreateSchema(name="Greataxe", item_type=ItemTypeEnum.WEAPON, weight=7.0, cost_gp=30.0, properties={"damage": "1d12 slashing", "type": "martial melee", "properties": ["heavy", "two-handed"]}),
    ItemCreateSchema(name="Greatsword", item_type=ItemTypeEnum.WEAPON, weight=6.0, cost_gp=50.0, properties={"damage": "2d6 slashing", "type": "martial melee", "properties": ["heavy", "two-handed"]}),
    ItemCreateSchema(name="Halberd", item_type=ItemTypeEnum.WEAPON, weight=6.0, cost_gp=20.0, properties={"damage": "1d10 slashing", "type": "martial melee", "properties": ["heavy", "reach", "two-handed"]}),
    ItemCreateSchema(name="Lance", item_type=ItemTypeEnum.WEAPON, weight=6.0, cost_gp=10.0, properties={"damage": "1d12 piercing", "type": "martial melee", "properties": ["reach", "special"]}),
    ItemCreateSchema(name="Longsword", item_type=ItemTypeEnum.WEAPON, weight=3.0, cost_gp=15.0, properties={"damage": "1d8 slashing", "type": "martial melee", "properties": ["versatile (1d10)"]}),
    ItemCreateSchema(name="Maul", item_type=ItemTypeEnum.WEAPON, weight=10.0, cost_gp=10.0, properties={"damage": "2d6 bludgeoning", "type": "martial melee", "properties": ["heavy", "two-handed"]}),
    ItemCreateSchema(name="Morningstar", item_type=ItemTypeEnum.WEAPON, weight=4.0, cost_gp=15.0, properties={"damage": "1d8 piercing", "type": "martial melee", "properties": []}),
    ItemCreateSchema(name="Pike", item_type=ItemTypeEnum.WEAPON, weight=18.0, cost_gp=5.0, properties={"damage": "1d10 piercing", "type": "martial melee", "properties": ["heavy", "reach", "two-handed"]}),
    ItemCreateSchema(name="Rapier", item_type=ItemTypeEnum.WEAPON, weight=2.0, cost_gp=25.0, properties={"damage": "1d8 piercing", "type": "martial melee", "properties": ["finesse"]}),
    ItemCreateSchema(name="Scimitar", item_type=ItemTypeEnum.WEAPON, weight=3.0, cost_gp=25.0, properties={"damage": "1d6 slashing", "type": "martial melee", "properties": ["finesse", "light"]}),
    ItemCreateSchema(name="Shortsword", item_type=ItemTypeEnum.WEAPON, weight=2.0, cost_gp=10.0, properties={"damage": "1d6 piercing", "type": "martial melee", "properties": ["finesse", "light"]}),
    ItemCreateSchema(name="Trident", item_type=ItemTypeEnum.WEAPON, weight=4.0, cost_gp=5.0, properties={"damage": "1d6 piercing", "type": "martial melee", "properties": ["thrown (range 20/60)", "versatile (1d8)"]}),
    ItemCreateSchema(name="War pick", item_type=ItemTypeEnum.WEAPON, weight=2.0, cost_gp=5.0, properties={"damage": "1d8 piercing", "type": "martial melee", "properties": []}),
    ItemCreateSchema(name="Warhammer", item_type=ItemTypeEnum.WEAPON, weight=2.0, cost_gp=15.0, properties={"damage": "1d8 bludgeoning", "type": "martial melee", "properties": ["versatile (1d10)"]}),
    ItemCreateSchema(name="Whip", item_type=ItemTypeEnum.WEAPON, weight=3.0, cost_gp=2.0, properties={"damage": "1d4 slashing", "type": "martial melee", "properties": ["finesse", "reach"]}),
    ItemCreateSchema(name="Blowgun", item_type=ItemTypeEnum.WEAPON, weight=1.0, cost_gp=10.0, properties={"damage": "1 piercing", "type": "martial ranged", "properties": ["ammunition (range 25/100)", "loading"]}),
    ItemCreateSchema(name="Hand Crossbow", item_type=ItemTypeEnum.WEAPON, weight=3.0, cost_gp=75.0, properties={"damage": "1d6 piercing", "type": "martial ranged", "properties": ["ammunition (range 30/120)", "light", "loading"]}),
    ItemCreateSchema(name="Heavy Crossbow", item_type=ItemTypeEnum.WEAPON, weight=18.0, cost_gp=50.0, properties={"damage": "1d10 piercing", "type": "martial ranged", "properties": ["ammunition (range 100/400)", "heavy", "loading", "two-handed"]}),
    ItemCreateSchema(name="Longbow", item_type=ItemTypeEnum.WEAPON, weight=2.0, cost_gp=50.0, properties={"damage": "1d8 piercing", "type": "martial ranged", "properties": ["ammunition (range 150/600)", "heavy", "two-handed"]}),
    ItemCreateSchema(name="Net", item_type=ItemTypeEnum.WEAPON, weight=3.0, cost_gp=1.0, properties={"damage": "", "type": "martial ranged", "properties": ["special", "thrown (range 5/15)"]}),
    
    # --- Potions ---
    ItemCreateSchema(name="Potion of Greater Healing", item_type=ItemTypeEnum.POTION, weight=0.5, cost_gp=250.0, properties={"effect": "Restores 4d4+4 hit points."}),
    ItemCreateSchema(name="Potion of Fire Breath", item_type=ItemTypeEnum.POTION, weight=0.5, cost_gp=0, properties={"effect": "After drinking this potion, you can use a bonus action to exhale fire at a target within 30 feet of you."}),
    ItemCreateSchema(name="Potion of Invisibility", item_type=ItemTypeEnum.POTION, weight=0.5, cost_gp=0, properties={"effect": "This potion's container looks empty but feels as though it holds liquid. When you drink it, you become invisible for 1 hour."}),
    ItemCreateSchema(name="Potion of Animal Friendship", item_type=ItemTypeEnum.POTION, weight=0.5, cost_gp=0, properties={"rarity": "uncommon", "effect": "When you drink this potion, you can cast the animal friendship spell (save DC 13) for 1 hour at will."}),
    ItemCreateSchema(name="Potion of Clairvoyance", item_type=ItemTypeEnum.POTION, weight=0.5, cost_gp=0, properties={"rarity": "rare", "effect": "When you drink this potion, you gain the effect of the clairvoyance spell."}),
    ItemCreateSchema(name="Potion of Climbing", item_type=ItemTypeEnum.POTION, weight=0.5, cost_gp=0, properties={"rarity": "common", "effect": "When you drink this potion, you gain a climbing speed equal to your walking speed for 1 hour."}),
    ItemCreateSchema(name="Potion of Diminution", item_type=ItemTypeEnum.POTION, weight=0.5, cost_gp=0, properties={"rarity": "rare", "effect": "When you drink this potion, you gain the 'reduce' effect of the enlarge/reduce spell for 1d4 hours (no concentration required)."}),
    ItemCreateSchema(name="Potion of Flying", item_type=ItemTypeEnum.POTION, weight=0.5, cost_gp=0, properties={"rarity": "very rare", "effect": "When you drink this potion, you gain a flying speed equal to your walking speed for 1 hour and can hover."}),
    ItemCreateSchema(name="Potion of Gaseous Form", item_type=ItemTypeEnum.POTION, weight=0.5, cost_gp=0, properties={"rarity": "rare", "effect": "When you drink this potion, you gain the effect of the gaseous form spell for 1 hour (no concentration required) or until you end the effect as a bonus action."}),
    ItemCreateSchema(name="Potion of Giant Strength (Hill)", item_type=ItemTypeEnum.POTION, weight=0.5, cost_gp=0, properties={"rarity": "uncommon", "effect": "When you drink this potion, your Strength score changes to 21 for 1 hour."}),
    ItemCreateSchema(name="Potion of Giant Strength (Frost/Stone)", item_type=ItemTypeEnum.POTION, weight=0.5, cost_gp=0, properties={"rarity": "rare", "effect": "When you drink this potion, your Strength score changes to 23 for 1 hour."}),
    ItemCreateSchema(name="Potion of Giant Strength (Fire)", item_type=ItemTypeEnum.POTION, weight=0.5, cost_gp=0, properties={"rarity": "rare", "effect": "When you drink this potion, your Strength score changes to 25 for 1 hour."}),
    ItemCreateSchema(name="Potion of Giant Strength (Cloud)", item_type=ItemTypeEnum.POTION, weight=0.5, cost_gp=0, properties={"rarity": "very rare", "effect": "When you drink this potion, your Strength score changes to 27 for 1 hour."}),
    ItemCreateSchema(name="Potion of Giant Strength (Storm)", item_type=ItemTypeEnum.POTION, weight=0.5, cost_gp=0, properties={"rarity": "legendary", "effect": "When you drink this potion, your Strength score changes to 29 for 1 hour."}),
    ItemCreateSchema(name="Potion of Growth", item_type=ItemTypeEnum.POTION, weight=0.5, cost_gp=0, properties={"rarity": "uncommon", "effect": "When you drink this potion, you gain the 'enlarge' effect of the enlarge/reduce spell for 1d4 hours (no concentration required)."}),
    ItemCreateSchema(name="Potion of Heroism", item_type=ItemTypeEnum.POTION, weight=0.5, cost_gp=0, properties={"rarity": "rare", "effect": "For 1 hour after drinking it, you gain 10 temporary hit points that last for 1 hour. For the same duration, you are under the effect of the bless spell (no concentration required)."}),
    ItemCreateSchema(name="Potion of Mind Reading", item_type=ItemTypeEnum.POTION, weight=0.5, cost_gp=0, properties={"rarity": "rare", "effect": "When you drink this potion, you gain the effect of the detect thoughts spell (save DC 13)."}),
    ItemCreateSchema(name="Potion of Poison", item_type=ItemTypeEnum.POTION, weight=0.5, cost_gp=0, properties={"rarity": "uncommon", "effect": "This concoction looks, smells, and tastes like a Potion of Healing. However, it is actually poison masked by illusion magic. An identify spell reveals its true nature. If you drink it, you take 3d6 poison damage, and you must succeed on a DC 13 Constitution saving throw or be poisoned."}),
    ItemCreateSchema(name="Potion of Resistance", item_type=ItemTypeEnum.POTION, weight=0.5, cost_gp=0, properties={"rarity": "uncommon", "effect": "When you drink this potion, you gain resistance to one type of damage for 1 hour. The DM chooses the type or determines it randomly."}),
    ItemCreateSchema(name="Potion of Superior Healing", item_type=ItemTypeEnum.POTION, weight=0.5, cost_gp=0, properties={"rarity": "very rare", "effect": "You regain 8d4 + 8 hit points when you drink this potion."}),
    ItemCreateSchema(name="Potion of Supreme Healing", item_type=ItemTypeEnum.POTION, weight=0.5, cost_gp=0, properties={"rarity": "legendary", "effect": "You regain 10d4 + 20 hit points when you drink this potion."}),
    ItemCreateSchema(name="Potion of Water Breathing", item_type=ItemTypeEnum.POTION, weight=0.5, cost_gp=0, properties={"rarity": "uncommon", "effect": "You can breathe underwater for 1 hour after drinking this potion."}),
    ItemCreateSchema(name="Potion of Healing", item_type=ItemTypeEnum.POTION, weight=0.5, cost_gp=50.0, properties={"rarity": "common", "effect": "You regain 2d4 + 2 hit points when you drink this potion."}),
    
    # --- Wonderous Items ---
    ItemCreateSchema(name="Boots of Elvenkind", item_type=ItemTypeEnum.WONDROUS_ITEM, weight=1.0, cost_gp=0, properties={"rarity": "uncommon", "effect": "While you wear these boots, your steps make no sound, regardless of the surface you are moving across. You also have advantage on Dexterity (Stealth) checks that rely on moving silently."}),
    ItemCreateSchema(name="Amulet of Health", item_type=ItemTypeEnum.WONDROUS_ITEM, weight=1.0, cost_gp=0, properties={"rarity": "rare", "attunement": True, "effect": "Your Constitution score is 19 while you wear this amulet."}),
    ItemCreateSchema(name="Amulet of Proof against Detection and Location", item_type=ItemTypeEnum.WONDROUS_ITEM, weight=1.0, cost_gp=0, properties={"rarity": "uncommon", "attunement": True, "effect": "While you wear it, you are hidden from divination magic. You can't be targeted by any divination magic or perceived through magical scrying sensors."}),
    ItemCreateSchema(name="Bag of Holding", item_type=ItemTypeEnum.WONDROUS_ITEM, weight=15.0, cost_gp=0, properties={"rarity": "uncommon", "effect": "This bag has an interior space considerably larger than its outside dimensions, roughly 2 feet in diameter at the mouth and 4 feet deep. The bag can hold up to 500 pounds, not exceeding a volume of 64 cubic feet."}),
    ItemCreateSchema(name="Bag of Tricks", item_type=ItemTypeEnum.WONDROUS_ITEM, weight=0.5, cost_gp=0, properties={"rarity": "uncommon", "effect": "This ordinary bag, made from gray, rust, or tan cloth, appears empty. Reaching inside the bag, however, reveals the presence of a small, fuzzy object. You can use an action to pull the fuzzy object from the bag and throw it up to 20 feet. When the object lands, it transforms into a creature you determine by rolling a d8."}),
    ItemCreateSchema(name="Belt of Dwarvenkind", item_type=ItemTypeEnum.WONDROUS_ITEM, weight=1.0, cost_gp=0, properties={"rarity": "rare", "attunement": True, "effect": "While wearing this belt, you gain the following benefits: Your Constitution score increases by 2, to a maximum of 20. You have advantage on Charisma (Persuasion) checks made to interact with dwarves."}),
    ItemCreateSchema(name="Belt of Giant Strength (Hill)", item_type=ItemTypeEnum.WONDROUS_ITEM, weight=1.0, cost_gp=0, properties={"rarity": "rare", "attunement": True, "effect": "While wearing this belt, your Strength score changes to 21."}),
    ItemCreateSchema(name="Boots of Levitation", item_type=ItemTypeEnum.WONDROUS_ITEM, weight=1.0, cost_gp=0, properties={"rarity": "rare", "attunement": True, "effect": "While you wear these boots, you can use an action to cast the levitate spell on yourself at will."}),
    ItemCreateSchema(name="Boots of Speed", item_type=ItemTypeEnum.WONDROUS_ITEM, weight=1.0, cost_gp=0, properties={"rarity": "rare", "attunement": True, "effect": "While you wear these boots, you can use a bonus action and click the boots' heels together. If you do, the boots double your walking speed, and any creature that makes an opportunity attack against you has disadvantage on the attack roll. If you click your heels together again, you end the effect."}),
    ItemCreateSchema(name="Bracers of Archery", item_type=ItemTypeEnum.WONDROUS_ITEM, weight=1.0, cost_gp=0, properties={"rarity": "uncommon", "attunement": True, "effect": "While wearing these bracers, you have proficiency with the longbow and shortbow, and you gain a +2 bonus to damage rolls on ranged attacks made with such weapons."}),
    ItemCreateSchema(name="Bracers of Defense", item_type=ItemTypeEnum.WONDROUS_ITEM, weight=1.0, cost_gp=0, properties={"rarity": "rare", "attunement": True, "effect": "While wearing these bracers, you gain a +2 bonus to AC if you are wearing no armor and using no shield."}),
    ItemCreateSchema(name="Broom of Flying", item_type=ItemTypeEnum.WONDROUS_ITEM, weight=3.0, cost_gp=0, properties={"rarity": "uncommon", "effect": "This wooden broom, which weighs 3 pounds, has a flying speed of 50 feet and can carry up to 400 pounds."}),
    ItemCreateSchema(name="Cape of the Mountebank", item_type=ItemTypeEnum.WONDROUS_ITEM, weight=1.0, cost_gp=0, properties={"rarity": "rare", "attunement": True, "effect": "While wearing this cape, you can use it to cast the dimension door spell as an action. This property of the cape can't be used again until the next dawn."}),
    ItemCreateSchema(name="Carpet of Flying", item_type=ItemTypeEnum.WONDROUS_ITEM, weight=20.0, cost_gp=0, properties={"rarity": "very rare", "effect": "You can speak the carpet's command word as an action to make it fly. It can carry up to 800 pounds."}),
    ItemCreateSchema(name="Cloak of Elvenkind", item_type=ItemTypeEnum.WONDROUS_ITEM, weight=1.0, cost_gp=0, properties={"rarity": "uncommon", "attunement": True, "effect": "While you wear this cloak with its hood up, Wisdom (Perception) checks made to see you have disadvantage, and you have advantage on Dexterity (Stealth) checks made to hide."}),
    ItemCreateSchema(name="Cloak of Protection", item_type=ItemTypeEnum.WONDROUS_ITEM, weight=1.0, cost_gp=0, properties={"rarity": "uncommon", "attunement": True, "effect": "You gain a +1 bonus to AC and saving throws while you wear this cloak."}),
    ItemCreateSchema(name="Crystal Ball", item_type=ItemTypeEnum.WONDROUS_ITEM, weight=3.0, cost_gp=0, properties={"rarity": "very rare", "attunement": True, "effect": "You can use an action to cast the scrying spell (save DC 17) with it."}),
    ItemCreateSchema(name="Cube of Force", item_type=ItemTypeEnum.WONDROUS_ITEM, weight=1.0, cost_gp=0, properties={"rarity": "rare", "attunement": True, "effect": "This cube is about an inch across. Each face has a distinct marking on it that can be pressed. The cube starts with 36 charges, and it regains 1d20 expended charges daily at dawn."}),
    ItemCreateSchema(name="Decanter of Endless Water", item_type=ItemTypeEnum.WONDROUS_ITEM, weight=2.0, cost_gp=0, properties={"rarity": "uncommon", "effect": "This stoppered flask sloshes when shaken, as if it contains water. The decanter weighs 2 pounds. You can use an action to remove the stopper and speak one of three command words, whereupon an amount of fresh water or salt water (your choice) pours out of the flask."}),
    ItemCreateSchema(name="Dimensional Shackles", item_type=ItemTypeEnum.WONDROUS_ITEM, weight=5.0, cost_gp=0, properties={"rarity": "rare", "effect": "You can use an action to place these shackles on an incapacitated creature. The shackles adjust to fit a creature of Small to Large size. In addition to serving as mundane manacles, the shackles prevent a creature from using any method of extradimensional movement, including teleportation or travel to a different plane of existence."}),
    ItemCreateSchema(name="Figurine of Wondrous Power, Silver Raven", item_type=ItemTypeEnum.WONDROUS_ITEM, weight=0.1, cost_gp=0, properties={"rarity": "uncommon", "effect": "This silver statuette of a raven can become a living raven for up to 12 hours. Once it has been used, it can't be used again until 2 days have passed."}),
    ItemCreateSchema(name="Gauntlets of Ogre Power", item_type=ItemTypeEnum.WONDROUS_ITEM, weight=2.0, cost_gp=0, properties={"rarity": "uncommon", "attunement": True, "effect": "Your Strength score is 19 while you wear these gauntlets."}),
    ItemCreateSchema(name="Gem of Seeing", item_type=ItemTypeEnum.WONDROUS_ITEM, weight=0.1, cost_gp=0, properties={"rarity": "rare", "attunement": True, "effect": "This gem has 3 charges. As an action, you can speak the gem's command word and expend 1 charge. For the next 10 minutes, you have truesight out to a range of 120 feet."}),
    ItemCreateSchema(name="Goggles of Night", item_type=ItemTypeEnum.WONDROUS_ITEM, weight=0.1, cost_gp=0, properties={"rarity": "uncommon", "attunement": True, "effect": "While wearing these dark lenses, you have darkvision out to a range of 60 feet."}),
    ItemCreateSchema(name="Headband of Intellect", item_type=ItemTypeEnum.WONDROUS_ITEM, weight=1.0, cost_gp=0, properties={"rarity": "uncommon", "attunement": True, "effect": "Your Intelligence score is 19 while you wear this headband."}),
    ItemCreateSchema(name="Helm of Comprehending Languages", item_type=ItemTypeEnum.WONDROUS_ITEM, weight=1.0, cost_gp=0, properties={"rarity": "uncommon", "attunement": True, "effect": "While wearing this helm, you can use an action to cast the comprehend languages spell from it at will."}),
    ItemCreateSchema(name="Immovable Rod", item_type=ItemTypeEnum.WONDROUS_ITEM, weight=2.0, cost_gp=0, properties={"rarity": "uncommon", "effect": "This flat iron rod has a button on one end. You can use an action to press the button, which causes the rod to become magically fixed in place. Until you or another creature uses an action to push the button again, the rod doesn't move, even if it is defying gravity."}),
    ItemCreateSchema(name="Iron Bands of Bilarro", item_type=ItemTypeEnum.WONDROUS_ITEM, weight=1.0, cost_gp=0, properties={"rarity": "rare", "effect": "You can use an action to speak the command word and throw the bands at a Huge or smaller creature you can see within 60 feet of you. The bands expand to entangle the target, which must succeed on a DC 17 Dexterity saving throw or be restrained."}),
    ItemCreateSchema(name="Lantern of Revealing", item_type=ItemTypeEnum.WONDROUS_ITEM, weight=2.0, cost_gp=0, properties={"rarity": "uncommon", "effect": "While lit, this hooded lantern burns for 6 hours on 1 pint of oil, shedding bright light in a 30-foot radius and dim light for an additional 30 feet. Invisible creatures and objects are visible as long as they are in the lantern's bright light."}),
    ItemCreateSchema(name="Pearl of Power", item_type=ItemTypeEnum.WONDROUS_ITEM, weight=0.0, cost_gp=0, properties={"rarity": "uncommon", "attunement": True, "effect": "While this pearl is on your person, you can use an action to speak its command word and regain one expended spell slot of 3rd level or lower. Once you have used the pearl, it can't be used again until the next dawn."}),
    ItemCreateSchema(name="Periapt of Health", item_type=ItemTypeEnum.WONDROUS_ITEM, weight=1.0, cost_gp=0, properties={"rarity": "uncommon", "attunement": True, "effect": "You are immune to contracting any disease while you wear this pendant. If you are already infected with a disease, the effects of the disease are suppressed while you wear the pendant."}),
    ItemCreateSchema(name="Periapt of Wound Closure", item_type=ItemTypeEnum.WONDROUS_ITEM, weight=1.0, cost_gp=0, properties={"rarity": "uncommon", "attunement": True, "effect": "While you wear this pendant, you stabilize whenever you are dying at the start of your turn. In addition, whenever you roll a Hit Die to regain hit points, double the number of hit points it restores."}),
    ItemCreateSchema(name="Portable Hole", item_type=ItemTypeEnum.WONDROUS_ITEM, weight=0.0, cost_gp=0, properties={"rarity": "rare", "effect": "This fine black cloth, soft as silk, is folded up to the dimensions of a handkerchief. It unfolds into a circular sheet 6 feet in diameter. You can use an action to unfold a portable hole and place it on or against a solid surface, whereupon the portable hole creates an extradimensional hole 10 feet deep."}),
    ItemCreateSchema(name="Rope of Climbing", item_type=ItemTypeEnum.WONDROUS_ITEM, weight=3.0, cost_gp=0, properties={"rarity": "uncommon", "effect": "This 60-foot length of silk rope weighs 3 pounds and can hold up to 3,000 pounds. If you hold one end of the rope and use an action to speak the command word, the rope animates."}),
    ItemCreateSchema(name="Saddle of the Cavalier", item_type=ItemTypeEnum.WONDROUS_ITEM, weight=25.0, cost_gp=0, properties={"rarity": "uncommon", "effect": "While in this saddle on a mount, you can't be dismounted against your will if you're conscious, and you have advantage on saving throws made to avoid falling off your mount."}),
    ItemCreateSchema(name="Sending Stones", item_type=ItemTypeEnum.WONDROUS_ITEM, weight=1.0, cost_gp=0, properties={"rarity": "uncommon", "effect": "Sending stones come in pairs, with each smooth stone carved to match the other. While you touch one stone, you can use an action to cast the sending spell from it."}),
    ItemCreateSchema(name="Stone of Good Luck (Luckstone)", item_type=ItemTypeEnum.WONDROUS_ITEM, weight=0.5, cost_gp=0, properties={"rarity": "uncommon", "attunement": True, "effect": "While this polished agate is on your person, you gain a +1 bonus to ability checks and saving throws."}),
    ItemCreateSchema(name="Wind Fan", item_type=ItemTypeEnum.WONDROUS_ITEM, weight=1.0, cost_gp=0, properties={"rarity": "uncommon", "effect": "While holding this fan, you can use an action to cast the gust of wind spell (save DC 13) from it. Once used, the fan can't be used again until the next dawn."}),
    ItemCreateSchema(name="Winged Boots", item_type=ItemTypeEnum.WONDROUS_ITEM, weight=1.0, cost_gp=0, properties={"rarity": "uncommon", "attunement": True, "effect": "While you wear these boots, you have a flying speed equal to your walking speed. You can use the boots to fly for up to 4 hours, all at once or in several shorter flights, each one using a minimum of 1 minute from the duration."}),
    
    # --- Magic Armor ---
    ItemCreateSchema(name="Adamantine Armor", item_type=ItemTypeEnum.ARMOR, weight=0, cost_gp=0, properties={"rarity": "uncommon", "effect": "While wearing this armor, any critical hit against you becomes a normal hit."}),
    ItemCreateSchema(name="Mithral Armor", item_type=ItemTypeEnum.ARMOR, weight=0, cost_gp=0, properties={"rarity": "uncommon", "effect": "Mithral is a light, flexible metal. A mithral chain shirt or breastplate can be worn under normal clothes. If the armor normally imposes disadvantage on Dexterity (Stealth) checks or has a Strength requirement, the mithral version of the armor doesn't."}),
    ItemCreateSchema(name="Armor of Vulnerability", item_type=ItemTypeEnum.ARMOR, weight=45.0, cost_gp=0, properties={"rarity": "rare", "attunement": True, "effect": "While wearing this armor, you have resistance to one of the following damage types: bludgeoning, piercing, or slashing. The DM chooses the type or determines it randomly. Curse: This armor is cursed. You have vulnerability to two other damage types from the list."}),
    ItemCreateSchema(name="Demon Armor", item_type=ItemTypeEnum.ARMOR, weight=65.0, cost_gp=0, properties={"rarity": "very rare", "attunement": True, "effect": "While wearing this armor, you gain a +1 bonus to AC, and you can understand and speak Abyssal. In addition, the armor's clawed gauntlets turn unarmed strikes with your hands into magic weapons that deal slashing damage, with a +1 bonus to attack and damage rolls."}),
    ItemCreateSchema(name="Dwarven Plate", item_type=ItemTypeEnum.ARMOR, weight=65.0, cost_gp=0, properties={"rarity": "very rare", "attunement": True, "effect": "While wearing this armor, you gain a +2 bonus to AC. In addition, if an effect moves you against your will along the ground, you can use your reaction to reduce the distance you are moved by up to 10 feet."}),
    ItemCreateSchema(name="Elven Chain", item_type=ItemTypeEnum.ARMOR, weight=20.0, cost_gp=0, properties={"rarity": "rare", "attunement": False, "effect": "You gain a +1 bonus to AC while you wear this armor. You are considered proficient with this armor even if you lack proficiency with medium armor."}),
    ItemCreateSchema(name="Glamoured Studded Leather", item_type=ItemTypeEnum.ARMOR, weight=13.0, cost_gp=0, properties={"rarity": "rare", "attunement": True, "effect": "While wearing this armor, you gain a +1 bonus to AC. You can also use a bonus action to cause the armor to appear as a normal set of clothing or some other kind of armor."}),
    ItemCreateSchema(name="Plate Armor of Etherealness", item_type=ItemTypeEnum.ARMOR, weight=65.0, cost_gp=0, properties={"rarity": "legendary", "attunement": True, "effect": "While you're wearing this armor, you can speak its command word as an action to gain the effect of the etherealness spell, which lasts for 10 minutes or until you remove the armor or use an action to speak the command word again."}),

    # --- Magic Rings ---
    ItemCreateSchema(name="Ring of Animal Influence", item_type=ItemTypeEnum.RING, weight=0.0, cost_gp=0, properties={"rarity": "rare", "effect": "This ring has 3 charges, and it regains 1d3 expended charges daily at dawn. While wearing the ring, you can use an action to expend 1 of its charges to cast one of the following spells: animal friendship (save DC 13), fear (save DC 13), speak with animals."}),
    ItemCreateSchema(name="Ring of Evasion", item_type=ItemTypeEnum.RING, weight=0.0, cost_gp=0, properties={"rarity": "rare", "attunement": True, "effect": "This ring has 3 charges, and it regains 1d3 expended charges daily at dawn. When you fail a Dexterity saving throw while wearing it, you can use your reaction to expend 1 of its charges to succeed on that saving throw instead."}),
    ItemCreateSchema(name="Ring of Feather Falling", item_type=ItemTypeEnum.RING, weight=0.0, cost_gp=0, properties={"rarity": "rare", "attunement": True, "effect": "When you fall while wearing this ring, you descend 60 feet per round and take no falling damage."}),
    ItemCreateSchema(name="Ring of Free Action", item_type=ItemTypeEnum.RING, weight=0.0, cost_gp=0, properties={"rarity": "rare", "attunement": True, "effect": "While you wear this ring, difficult terrain doesn't cost you extra movement. In addition, magic can neither reduce your speed nor cause you to be paralyzed or restrained."}),
    ItemCreateSchema(name="Ring of Invisibility", item_type=ItemTypeEnum.RING, weight=0.0, cost_gp=0, properties={"rarity": "legendary", "attunement": True, "effect": "While wearing this ring, you can turn invisible as an action. Anything you are wearing or carrying is invisible with you."}),
    ItemCreateSchema(name="Ring of Jumping", item_type=ItemTypeEnum.RING, weight=0.0, cost_gp=0, properties={"rarity": "uncommon", "attunement": True, "effect": "While wearing this ring, you can cast the jump spell from it as a bonus action at will, but can target only yourself when you do so."}),
    ItemCreateSchema(name="Ring of Mind Shielding", item_type=ItemTypeEnum.RING, weight=0.0, cost_gp=0, properties={"rarity": "uncommon", "attunement": True, "effect": "While wearing this ring, you are immune to magic that allows other creatures to read your thoughts, determine whether you are lying, know your alignment, or know your creature type."}),
    ItemCreateSchema(name="Ring of Protection", item_type=ItemTypeEnum.RING, weight=0.0, cost_gp=0, properties={"rarity": "rare", "attunement": True, "effect": "You gain a +1 bonus to AC and saving throws while wearing this ring."}),
    ItemCreateSchema(name="Ring of Regeneration", item_type=ItemTypeEnum.RING, weight=0.0, cost_gp=0, properties={"rarity": "very rare", "attunement": True, "effect": "While wearing this ring, you regain 1d6 hit points every 10 minutes, provided that you have at least 1 hit point."}),
    ItemCreateSchema(name="Ring of Spell Storing", item_type=ItemTypeEnum.RING, weight=0.0, cost_gp=0, properties={"rarity": "rare", "attunement": True, "effect": "This ring stores spells cast into it, holding them until the attuned wearer uses them. The ring can store up to 5 levels worth of spells at a time."}),
    ItemCreateSchema(name="Ring of Swimming", item_type=ItemTypeEnum.RING, weight=0.0, cost_gp=0, properties={"rarity": "uncommon", "effect": "You have a swimming speed of 40 feet while wearing this ring."}),
    ItemCreateSchema(name="Ring of Telekinesis", item_type=ItemTypeEnum.RING, weight=0.0, cost_gp=0, properties={"rarity": "very rare", "attunement": True, "effect": "While wearing this ring, you can cast the telekinesis spell at will, but can target only objects that aren't being worn or carried."}),
    ItemCreateSchema(name="Ring of the Ram", item_type=ItemTypeEnum.RING, weight=0.0, cost_gp=0, properties={"rarity": "rare", "attunement": True, "effect": "This ring has 3 charges, and it regains 1d3 expended charges daily at dawn. While wearing the ring, you can use an action to expend 1 to 3 of its charges to attack one creature you can see within 60 feet of you."}),
    ItemCreateSchema(name="Ring of Warmth", item_type=ItemTypeEnum.RING, weight=0.0, cost_gp=0, properties={"rarity": "uncommon", "attunement": True, "effect": "While wearing this ring, you have resistance to cold damage. In addition, you and everything you wear and carry are unharmed by temperatures as low as -50 degrees Fahrenheit."}),
    ItemCreateSchema(name="Ring of Water Walking", item_type=ItemTypeEnum.RING, weight=0.0, cost_gp=0, properties={"rarity": "uncommon", "attunement": True, "effect": "While wearing this ring, you can stand on and move across any liquid surface as if it were solid ground."}),

    # --- Magic Weapons ---
    ItemCreateSchema(name="Weapon, +1", item_type=ItemTypeEnum.WEAPON, weight=0, cost_gp=0, properties={"rarity": "uncommon", "effect": "You have a +1 bonus to attack and damage rolls made with this magic weapon."}),
    ItemCreateSchema(name="Weapon, +2", item_type=ItemTypeEnum.WEAPON, weight=0, cost_gp=0, properties={"rarity": "rare", "effect": "You have a +2 bonus to attack and damage rolls made with this magic weapon."}),
    ItemCreateSchema(name="Weapon, +3", item_type=ItemTypeEnum.WEAPON, weight=0, cost_gp=0, properties={"rarity": "very rare", "effect": "You have a +3 bonus to attack and damage rolls made with this magic weapon."}),
    ItemCreateSchema(name="Dagger of Venom", item_type=ItemTypeEnum.WEAPON, weight=1.0, cost_gp=0, properties={"rarity": "rare", "attunement": True, "effect": "You gain a +1 bonus to attack and damage rolls made with this magic weapon. You can use an action to cause thick, black poison to coat the blade. The poison remains for 1 minute or until an attack using this weapon hits a creature."}),
    ItemCreateSchema(name="Dragon Slayer", item_type=ItemTypeEnum.WEAPON, weight=0, cost_gp=0, properties={"rarity": "rare", "attunement": True, "effect": "You gain a +1 bonus to attack and damage rolls made with this magic weapon. When you hit a dragon with this weapon, the dragon takes an extra 3d6 damage of the weapon's type."}),
    ItemCreateSchema(name="Flame Tongue", item_type=ItemTypeEnum.WEAPON, weight=0, cost_gp=0, properties={"rarity": "rare", "attunement": True, "effect": "You can use a bonus action to speak this magic sword's command word, causing flames to erupt from the blade. These flames shed bright light in a 40-foot radius and dim light for an additional 40 feet. While the sword is ablaze, it deals an extra 2d6 fire damage to any target it hits."}),
    ItemCreateSchema(name="Frost Brand", item_type=ItemTypeEnum.WEAPON, weight=0, cost_gp=0, properties={"rarity": "very rare", "attunement": True, "effect": "When you hit with an attack using this magic sword, the target takes an extra 1d6 cold damage. In addition, while you hold the sword, you have resistance to fire damage."}),
    ItemCreateSchema(name="Giant Slayer", item_type=ItemTypeEnum.WEAPON, weight=0, cost_gp=0, properties={"rarity": "rare", "attunement": True, "effect": "You gain a +1 bonus to attack and damage rolls made with this magic weapon. When you hit a giant with it, the giant takes an extra 2d6 damage of the weapon's type."}),
    ItemCreateSchema(name="Holy Avenger", item_type=ItemTypeEnum.WEAPON, weight=3.0, cost_gp=0, properties={"rarity": "legendary", "attunement": "by a paladin", "effect": "You gain a +3 bonus to attack and damage rolls made with this magic weapon. When you hit a fiend or an undead with it, that creature takes an extra 2d10 radiant damage. While you hold the drawn sword, it creates an aura in a 10-foot radius around you."}),
    ItemCreateSchema(name="Javelin of Lightning", item_type=ItemTypeEnum.WEAPON, weight=2.0, cost_gp=0, properties={"rarity": "uncommon", "effect": "This javelin is a magic weapon. When you hurl it and speak its command word, it transforms into a bolt of lightning, forming a line 5 feet wide that extends out from you to a target within 120 feet."}),
    ItemCreateSchema(name="Mace of Disruption", item_type=ItemTypeEnum.WEAPON, weight=4.0, cost_gp=0, properties={"rarity": "rare", "attunement": True, "effect": "When you hit a fiend or an undead with this magic weapon, that creature takes an extra 2d6 radiant damage. If the target has 25 hit points or fewer after taking this damage, it must succeed on a DC 15 Wisdom saving throw or be destroyed."}),
    ItemCreateSchema(name="Mace of Smiting", item_type=ItemTypeEnum.WEAPON, weight=4.0, cost_gp=0, properties={"rarity": "rare", "effect": "You gain a +1 bonus to attack and damage rolls made with this magic weapon. The bonus increases to +3 when you use the mace to attack a construct."}),
    ItemCreateSchema(name="Mace of Terror", item_type=ItemTypeEnum.WEAPON, weight=4.0, cost_gp=0, properties={"rarity": "rare", "attunement": True, "effect": "This magic weapon has 3 charges. While holding it, you can use an action and expend 1 charge to release a wave of terror. Each creature of your choice in a 30-foot radius extending from you must succeed on a DC 15 Wisdom saving throw or become frightened of you for 1 minute."}),
    ItemCreateSchema(name="Nine Lives Stealer", item_type=ItemTypeEnum.WEAPON, weight=3.0, cost_gp=0, properties={"rarity": "very rare", "attunement": True, "effect": "This longsword has 9 charges. If you score a critical hit against a creature that has fewer than 100 hit points, it must succeed on a DC 15 Constitution saving throw or be slain instantly as the sword tears its life force from its body (a construct or an undead is immune)."}),
    ItemCreateSchema(name="Oathbow", item_type=ItemTypeEnum.WEAPON, weight=2.0, cost_gp=0, properties={"rarity": "very rare", "attunement": True, "effect": "When you nock an arrow on this bow, you can speak its command word to declare a sworn enemy. That creature becomes your sworn enemy for the next 24 hours, or until it dies or you declare a new sworn enemy."}),
    ItemCreateSchema(name="Scimitar of Speed", item_type=ItemTypeEnum.WEAPON, weight=3.0, cost_gp=0, properties={"rarity": "very rare", "attunement": True, "effect": "You gain a +2 bonus to attack and damage rolls made with this magic sword. In addition, you can make one attack with it as a bonus action on each of your turns."}),
    ItemCreateSchema(name="Sun Blade", item_type=ItemTypeEnum.WEAPON, weight=2.0, cost_gp=0, properties={"rarity": "rare", "attunement": True, "effect": "This item appears to be a longsword hilt. While grasping the hilt, you can use a bonus action to cause a blade of pure radiance to spring into existence, or make the blade disappear. You have a +2 bonus to attack and damage rolls made with this weapon, which deals radiant damage instead of slashing damage."}),
    ItemCreateSchema(name="Sword of Life Stealing", item_type=ItemTypeEnum.WEAPON, weight=3.0, cost_gp=0, properties={"rarity": "rare", "attunement": True, "effect": "When you hit a creature with an attack using this magic sword, the target takes an extra 3d6 necrotic damage, provided that the target isn't a construct or an undead. You regain hit points equal to half the amount of necrotic damage dealt."}),
    ItemCreateSchema(name="Sword of Sharpness", item_type=ItemTypeEnum.WEAPON, weight=3.0, cost_gp=0, properties={"rarity": "very rare", "attunement": True, "effect": "When you attack an object with this magic sword and hit, maximize your weapon damage rolls against the target. When you attack a creature with this weapon and roll a 20 on the attack roll, that target takes an extra 4d6 slashing damage."}),
    ItemCreateSchema(name="Trident of Fish Command", item_type=ItemTypeEnum.WEAPON, weight=4.0, cost_gp=0, properties={"rarity": "uncommon", "attunement": True, "effect": "This trident is a magic weapon. It has 3 charges. While you carry it, you can use an action and expend 1 charge to cast dominate beast (save DC 15) from it on a beast that has an innate swimming speed."}),
    ItemCreateSchema(name="Vicious Weapon", item_type=ItemTypeEnum.WEAPON, weight=0, cost_gp=0, properties={"rarity": "rare", "effect": "When you roll a 20 on your attack roll with this magic weapon, the target takes an extra 2d6 damage of the weapon's type."}),
    ItemCreateSchema(name="Vorpal Sword", item_type=ItemTypeEnum.WEAPON, weight=3.0, cost_gp=0, properties={"rarity": "legendary", "attunement": True, "effect": "You gain a +3 bonus to attack and damage rolls made with this magic weapon. In addition, the weapon ignores resistance to slashing damage. When you attack a creature that has at least one head with this weapon and roll a 20 on the attack roll, you cut off one of the creature's heads."}),

]
