from app.schemas.spell import SpellCreate as SpellCreateSchema
from app.models.spell import SchoolOfMagicEnum

PREDEFINED_SPELLS = [
    # Cantrips (Level 0)
    SpellCreateSchema(name="Light", description="You touch one object... sheds bright light...", higher_level=None, range="Touch", components="V, M", material="A firefly or phosphorescent moss", ritual=False, duration="1 hour", concentration=False, casting_time="1 action", level=0, school=SchoolOfMagicEnum.EVOCATION, dnd_classes=["Bard", "Cleric", "Sorcerer", "Wizard"], source_book="SRD"),
    SpellCreateSchema(name="Mage Hand", description="A spectral, floating hand appears...", higher_level=None, range="30 feet", components="V, S", material=None, ritual=False, duration="1 minute", concentration=False, casting_time="1 action", level=0, school=SchoolOfMagicEnum.CONJURATION, dnd_classes=["Bard", "Sorcerer", "Warlock", "Wizard"], source_book="SRD"),
    SpellCreateSchema(name="Ray of Frost", description="A frigid beam of blue-white light streaks towards a creature...", higher_level="The spell's damage increases by 1d8 when you reach 5th level (2d8), 11th level (3d8), and 17th level (4d8).", range="60 feet", components="V, S", material=None, ritual=False, duration="Instantaneous", concentration=False, casting_time="1 action", level=0, school=SchoolOfMagicEnum.EVOCATION, dnd_classes=["Sorcerer", "Wizard"], source_book="SRD"),
    SpellCreateSchema(name="Prestidigitation", description="This spell is a minor magical trick that novice spellcasters use for practice...", higher_level=None, range="10 feet", components="V, S", material=None, ritual=False, duration="Up to 1 hour", concentration=False, casting_time="1 action", level=0, school=SchoolOfMagicEnum.TRANSMUTATION, dnd_classes=["Bard", "Sorcerer", "Warlock", "Wizard"], source_book="SRD"),
    SpellCreateSchema(name="Acid Splash", description="You hurl a bubble of acid...", higher_level="The spell's damage increases by 1d6 when you reach 5th level (2d6), 11th level (3d6), and 17th level (4d6).", range="60 feet", components="V, S", material=None, ritual=False, duration="Instantaneous", concentration=False, casting_time="1 action", level=0, school=SchoolOfMagicEnum.CONJURATION, dnd_classes=["Sorcerer", "Wizard"], source_book="SRD"),
    SpellCreateSchema(name="Fire Bolt", description="You hurl a mote of fire...", higher_level="The spell's damage increases by 1d10 when you reach 5th level (2d10), 11th level (3d10), and 17th level (4d10).", range="120 feet", components="V, S", material=None, ritual=False, duration="Instantaneous", concentration=False, casting_time="1 action", level=0, school=SchoolOfMagicEnum.EVOCATION, dnd_classes=["Sorcerer", "Wizard"], source_book="SRD"),
    # Level 1 Spells
    SpellCreateSchema(name="Magic Missile", description="You create three glowing darts...", higher_level="When you cast this spell using a spell slot of 2nd level or higher, the spell creates one more dart for each slot level above 1st.", range="120 feet", components="V, S", material=None, ritual=False, duration="Instantaneous", concentration=False, casting_time="1 action", level=1, school=SchoolOfMagicEnum.EVOCATION, dnd_classes=["Sorcerer", "Wizard"], source_book="SRD"),
    SpellCreateSchema(name="Mage Armor", description="You touch a willing creature who isn’t wearing armor...", higher_level=None, range="Touch", components="V, S, M", material="A piece of cured leather", ritual=False, duration="8 hours", concentration=False, casting_time="1 action", level=1, school=SchoolOfMagicEnum.ABJURATION, dnd_classes=["Sorcerer", "Wizard"], source_book="SRD"),
    SpellCreateSchema(name="Shield", description="An invisible barrier of magical force appears and protects you...", higher_level=None, range="Self", components="V, S", material=None, ritual=False, duration="1 round", concentration=False, casting_time="1 reaction, which you take when you are hit by an attack or targeted by the magic missile spell", level=1, school=SchoolOfMagicEnum.ABJURATION, dnd_classes=["Sorcerer", "Wizard"], source_book="SRD"),
    SpellCreateSchema(name="Sleep", description="This spell sends creatures into a magical slumber...", higher_level="When you cast this spell using a spell slot of 2nd level or higher, you can affect an additional 2d8 hit points of creatures for each slot level above 1st.", range="90 feet", components="V, S, M", material="A pinch of fine sand, rose petals, or a cricket", ritual=False, duration="1 minute", concentration=False, casting_time="1 action", level=1, school=SchoolOfMagicEnum.ENCHANTMENT, dnd_classes=["Bard", "Sorcerer", "Wizard"], source_book="SRD"),
    SpellCreateSchema(name="Burning Hands", description="As you hold your hands with thumbs touching and fingers spread, a thin sheet of flames shoots forth...", higher_level="When you cast this spell using a spell slot of 2nd level or higher, the damage increases by 1d6 for each slot level above 1st.", range="Self (15-foot cone)", components="V, S", material=None, ritual=False, duration="Instantaneous", concentration=False, casting_time="1 action", level=1, school=SchoolOfMagicEnum.EVOCATION, dnd_classes=["Sorcerer", "Wizard"], source_book="SRD"),
    SpellCreateSchema(name="Charm Person", description="You attempt to charm a humanoid you can see within range...", higher_level="When you cast this spell using a spell slot of 2nd level or higher, you can target one additional creature for each slot level above 1st.", range="30 feet", components="V, S", material=None, ritual=False, duration="1 hour", concentration=False, casting_time="1 action", level=1, school=SchoolOfMagicEnum.ENCHANTMENT, dnd_classes=["Bard", "Druid", "Sorcerer", "Warlock", "Wizard"], source_book="SRD"),
    SpellCreateSchema(name="Feather Fall", description="Choose up to five falling creatures within range...", higher_level=None, range="60 feet", components="V, M", material="A small feather or a piece of down", ritual=False, duration="1 minute", concentration=False, casting_time="1 reaction, which you take when you or a creature within 60 feet of you falls", level=1, school=SchoolOfMagicEnum.TRANSMUTATION, dnd_classes=["Bard", "Sorcerer", "Wizard"], source_book="SRD"),
    # Level 2 Spells
    SpellCreateSchema(name="Misty Step", description="Briefly surrounded by silvery mist, you teleport up to 30 feet to an unoccupied space that you can see.", higher_level=None, range="Self", components="V", material=None, ritual=False, duration="Instantaneous", concentration=False, casting_time="1 bonus action", level=2, school=SchoolOfMagicEnum.CONJURATION, dnd_classes=["Sorcerer", "Warlock", "Wizard"], source_book="SRD"),
    SpellCreateSchema(name="Mirror Image", description="Three illusory duplicates of yourself appear in your space...", higher_level=None, range="Self", components="V, S", material=None, ritual=False, duration="1 minute", concentration=False, casting_time="1 action", level=2, school=SchoolOfMagicEnum.ILLUSION, dnd_classes=["Bard", "Sorcerer", "Warlock", "Wizard"], source_book="SRD"),
    SpellCreateSchema(name="Scorching Ray", description="You create three rays of fire and hurl them at targets within range...", higher_level="When you cast this spell using a spell slot of 3rd level or higher, you create one additional ray for each slot level above 2nd.", range="120 feet", components="V, S", material=None, ritual=False, duration="Instantaneous", concentration=False, casting_time="1 action", level=2, school=SchoolOfMagicEnum.EVOCATION, dnd_classes=["Sorcerer", "Wizard"], source_book="SRD"),
    SpellCreateSchema(name="Web", description="You conjure a mass of thick, sticky webbing at a point of your choice within range...", higher_level=None, range="60 feet", components="V, S, M", material="A bit of spiderweb", ritual=False, duration="Concentration, up to 1 hour", concentration=True, casting_time="1 action", level=2, school=SchoolOfMagicEnum.CONJURATION, dnd_classes=["Sorcerer", "Wizard"], source_book="SRD"),
    # Level 3 Spells
    SpellCreateSchema(name="Fireball", description="A bright streak flashes from your pointing finger...", higher_level="When you cast this spell using a spell slot of 4th level or higher, the damage increases by 1d6 for each slot level above 3rd.", range="150 feet", components="V, S, M", material="A tiny ball of bat guano and sulfur", ritual=False, duration="Instantaneous", concentration=False, casting_time="1 action", level=3, school=SchoolOfMagicEnum.EVOCATION, dnd_classes=["Sorcerer", "Wizard"], source_book="SRD"),
    SpellCreateSchema(name="Fly", description="You touch a willing creature. The target gains a flying speed of 60 feet for the duration.", higher_level="When you cast this spell using a spell slot of 4th level or higher, you can target one additional creature for each slot level above 3rd.", range="Touch", components="V, S, M", material="A wing feather from any bird", ritual=False, duration="Concentration, up to 10 minutes", concentration=True, casting_time="1 action", level=3, school=SchoolOfMagicEnum.TRANSMUTATION, dnd_classes=["Sorcerer", "Warlock", "Wizard"], source_book="SRD"),
    SpellCreateSchema(name="Counterspell", description="You attempt to interrupt a creature in the process of casting a spell...", higher_level="If you cast this spell using a spell slot of 4th level or higher, the interrupted spell has no effect if its level is less than or equal to the level of the spell slot you used.", range="60 feet", components="S", material=None, ritual=False, duration="Instantaneous", concentration=False, casting_time="1 reaction, which you take when you see a creature within 60 feet of you casting a spell", level=3, school=SchoolOfMagicEnum.ABJURATION, dnd_classes=["Sorcerer", "Warlock", "Wizard"], source_book="SRD"),
]
