"""create conditions table

Revision ID: 031539bc36ab
Revises: a9a4c0bda7c3
Create Date: 2025-06-14 15:30:51.732985

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '031539bc36ab'
down_revision: Union[str, None] = 'a9a4c0bda7c3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - Manually Corrected ###
    op.create_table('conditions',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('conditions_pkey'))
    )
    op.create_index(op.f('ix_conditions_name'), 'conditions', ['name'], unique=True)
    op.create_index(op.f('ix_conditions_id'), 'conditions', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - Manually Corrected ###
    op.drop_index(op.f('ix_conditions_name'), table_name='conditions')
    op.drop_index(op.f('ix_conditions_id'), table_name='conditions')
    op.drop_table('conditions')
    # ### end Alembic commands ###

