"""add campaign_session and initiative_entry tables

Revision ID: 2a8974fc9812
Revises: 7a8b001d5d45
Create Date: 2025-06-17 11:18:06.246946

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2a8974fc9812'
down_revision: Union[str, None] = '7a8b001d5d45'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - Manually Corrected ###
    op.create_table('campaign_sessions',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('campaign_id', sa.Integer(), nullable=False),
        sa.Column('is_active', sa.Boolean(), nullable=False, server_default=sa.text('true')),
        sa.Column('map_state', sa.JSON(), server_default=sa.text("'{}'::jsonb"), nullable=True),
        sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_campaign_sessions_id'), 'campaign_sessions', ['id'], unique=False)
    op.create_index(op.f('ix_campaign_sessions_campaign_id'), 'campaign_sessions', ['campaign_id'], unique=False)

    op.create_table('initiative_entries',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('session_id', sa.Integer(), nullable=False),
        sa.Column('character_id', sa.Integer(), nullable=True),
        sa.Column('monster_name', sa.String(length=100), nullable=True),
        sa.Column('initiative_roll', sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(['character_id'], ['characters.id'], ),
        sa.ForeignKeyConstraint(['session_id'], ['campaign_sessions.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_initiative_entries_id'), 'initiative_entries', ['id'], unique=False)
    op.create_index(op.f('ix_initiative_entries_session_id'), 'initiative_entries', ['session_id'], unique=False)
    op.create_index(op.f('ix_initiative_entries_initiative_roll'), 'initiative_entries', ['initiative_roll'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - Manually Corrected ###
    op.drop_index(op.f('ix_initiative_entries_session_id'), table_name='initiative_entries')
    op.drop_index(op.f('ix_initiative_entries_initiative_roll'), table_name='initiative_entries')
    op.drop_index(op.f('ix_initiative_entries_id'), table_name='initiative_entries')
    op.drop_table('initiative_entries')
    op.drop_index(op.f('ix_campaign_sessions_id'), table_name='campaign_sessions')
    op.drop_index(op.f('ix_campaign_sessions_campaign_id'), table_name='campaign_sessions')
    op.drop_table('campaign_sessions')
    # ### end Alembic commands ###


