"""add_is_ascended_tier_to_characters

Revision ID: 3ba5cbbde9cc
Revises: 56f03f6e1298
Create Date: 2025-05-27 18:56:02.786230

"""
# Path: api/alembic_migrations/versions/<your_new_revision_id>_add_is_ascended_tier_to_characters.py

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
# from sqlalchemy.dialects import postgresql # Not needed for this specific migration

# revision identifiers, used by Alembic.
revision: str = '3ba5cbbde9cc' # Make sure this matches your file's actual revision ID
down_revision: Union[str, None] = '56f03f6e1298' # Should be the ID of the migration that created character_spells
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - Manually Corrected ###
    op.add_column('characters', 
                  sa.Column('is_ascended_tier', 
                            sa.Boolean(), 
                            nullable=False, 
                            server_default=sa.text('false'))) # Added server_default
    op.create_index(op.f('ix_characters_is_ascended_tier'), 'characters', ['is_ascended_tier'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - Manually Corrected ###
    op.drop_index(op.f('ix_characters_is_ascended_tier'), table_name='characters')
    op.drop_column('characters', 'is_ascended_tier')
    # ### end Alembic commands ###

