"""add_hit_die_type_and_pending_level_up_to_characters

Revision ID: 3dfac716a13d
Revises: 14c9c08f63aa
Create Date: 2025-05-29 13:16:40.525033

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3dfac716a13d'
down_revision: Union[str, None] = '14c9c08f63aa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('characters', sa.Column('hit_die_type', sa.Integer(), nullable=True))
    op.add_column('characters', sa.Column('has_pending_level_up', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.drop_index(op.f('ix_characters_is_ascended_tier'), table_name='characters')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_characters_is_ascended_tier'), 'characters', ['is_ascended_tier'], unique=False)
    op.drop_column('characters', 'has_pending_level_up')
    op.drop_column('characters', 'hit_die_type')
    # ### end Alembic commands ###


