# Path: api/alembic_migrations/versions/5e47228cc385_add_individual_ability_scores_remove_.py
"""add_individual_ability_scores_remove_json_from_character

Revision ID: 5e47228cc385
Revises: 008b06a1dd79
Create Date: 2025-05-26 16:10:20.364557

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5e47228cc385'
down_revision: Union[str, None] = '008b06a1dd79'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - MANUALLY ADJUSTED ###
    op.add_column('characters', sa.Column('strength', sa.Integer(), nullable=False, server_default=sa.text('10')))
    op.add_column('characters', sa.Column('dexterity', sa.Integer(), nullable=False, server_default=sa.text('10')))
    op.add_column('characters', sa.Column('constitution', sa.Integer(), nullable=False, server_default=sa.text('10')))
    op.add_column('characters', sa.Column('intelligence', sa.Integer(), nullable=False, server_default=sa.text('10')))
    op.add_column('characters', sa.Column('wisdom', sa.Integer(), nullable=False, server_default=sa.text('10')))
    op.add_column('characters', sa.Column('charisma', sa.Integer(), nullable=False, server_default=sa.text('10')))
    
    # It's often safer to drop the column *after* ensuring the new columns are populated,
    # especially if there was data to migrate from the old column to the new ones.
    # In our case, we are not migrating data from ability_scores JSON to the new columns
    # directly in this migration, so the order is less critical but dropping last is fine.
    op.drop_column('characters', 'ability_scores')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # When re-adding the ability_scores column, it will be nullable as originally defined.
    op.add_column('characters', sa.Column('ability_scores', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.drop_column('characters', 'charisma')
    op.drop_column('characters', 'wisdom')
    op.drop_column('characters', 'intelligence')
    op.drop_column('characters', 'constitution')
    op.drop_column('characters', 'dexterity')
    op.drop_column('characters', 'strength')
    # ### end Alembic commands ###