"""add_roguish_archetype_to_characters

Revision ID: 61c53f16ce6f
Revises: fa6d854216b3
Create Date: 2025-05-31 14:54:40.253125

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '61c53f16ce6f'
down_revision: Union[str, None] = 'fa6d854216b3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('characters', sa.Column('roguish_archetype', sa.Enum('THIEF', 'ASSASSIN', 'ARCANE_TRICKSTER', name='roguisharchetypeenum'), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('characters', 'roguish_archetype')
    # ### end Alembic commands ###
