"""change_has_pending_level_up_to_level_up_status_string

Revision ID: 62612bd065e4
Revises: 16e4a28ecf70
Create Date: 2025-05-30 14:30:32.058734

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '62612bd065e4'
down_revision: Union[str, None] = '16e4a28ecf70'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('characters', sa.Column('level_up_status', sa.String(length=50), nullable=True))
    op.drop_column('characters', 'has_pending_level_up')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('characters', sa.Column('has_pending_level_up', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False))
    op.drop_column('characters', 'level_up_status')
    # ### end Alembic commands ###
