"""add subraces column to races table

Revision ID: 720d2b091075
Revises: 031539bc36ab
Create Date: 2025-06-14 17:24:42.623158

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '720d2b091075'
down_revision: Union[str, None] = '031539bc36ab'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - Manually Corrected ###
    op.add_column('races', sa.Column('subraces', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - Manually Corrected ###
    op.drop_column('races', 'subraces')
    # ### end Alembic commands ###
