""""add completed_level_up_choices to characters

Revision ID: 7a8b001d5d45
Revises: 720d2b091075
Create Date: 2025-06-16 14:50:12.380726

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7a8b001d5d45'
down_revision: Union[str, None] = '720d2b091075'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - Manually Corrected ###
    op.add_column('characters', sa.Column('completed_level_up_choices', sa.JSON(), server_default=sa.text("'[]'"), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - Manually Corrected ###
    op.drop_column('characters', 'completed_level_up_choices')
    # ### end Alembic commands ###
