"""add_saving_throw_proficiencies_to_characters

Revision ID: a075cd5f2a45
Revises: d32bdc897e38
Create Date: 2025-06-02 21:22:16.280710

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a075cd5f2a45'
down_revision: Union[str, None] = 'd32bdc897e38'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('characters', sa.Column('st_prof_strength', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.add_column('characters', sa.Column('st_prof_dexterity', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.add_column('characters', sa.Column('st_prof_constitution', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.add_column('characters', sa.Column('st_prof_intelligence', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.add_column('characters', sa.Column('st_prof_wisdom', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.add_column('characters', sa.Column('st_prof_charisma', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('characters', 'st_prof_charisma')
    op.drop_column('characters', 'st_prof_wisdom')
    op.drop_column('characters', 'st_prof_intelligence')
    op.drop_column('characters', 'st_prof_constitution')
    op.drop_column('characters', 'st_prof_dexterity')
    op.drop_column('characters', 'st_prof_strength')
    # ### end Alembic commands ###
