"""create backgrounds table

Revision ID: a9a4c0bda7c3
Revises: e9c18c76fc2d
Create Date: 2025-06-14 15:30:51.732985

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a9a4c0bda7c3'
down_revision: Union[str, None] = 'e9c18c76fc2d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - Manually Corrected ###
    op.create_table('backgrounds',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('skill_proficiencies', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('tool_proficiencies', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('languages', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('equipment', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('feature', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('backgrounds_pkey'))
    )
    op.create_index(op.f('ix_backgrounds_name'), 'backgrounds', ['name'], unique=True)
    op.create_index(op.f('ix_backgrounds_id'), 'backgrounds', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - Manually Corrected ###
    op.drop_index(op.f('ix_backgrounds_name'), table_name='backgrounds')
    op.drop_index(op.f('ix_backgrounds_id'), table_name='backgrounds')
    op.drop_table('backgrounds')
    # ### end Alembic commands ###

