"""add_full_currency_to_characters

Revision ID: d32bdc897e38
Revises: c44e28185c21
Create Date: 2025-06-02 17:33:16.194588

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd32bdc897e38'
down_revision: Union[str, None] = 'c44e28185c21'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('characters', sa.Column('currency_pp', sa.Integer(), server_default=sa.text('0'), nullable=False))
    op.add_column('characters', sa.Column('currency_ep', sa.Integer(), server_default=sa.text('0'), nullable=False))
    op.add_column('characters', sa.Column('currency_sp', sa.Integer(), server_default=sa.text('0'), nullable=False))
    op.add_column('characters', sa.Column('currency_cp', sa.Integer(), server_default=sa.text('0'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('characters', 'currency_cp')
    op.drop_column('characters', 'currency_sp')
    op.drop_column('characters', 'currency_ep')
    op.drop_column('characters', 'currency_pp')
    # ### end Alembic commands ###
