"""create races table

Revision ID: e9c18c76fc2d
Revises: ea8382d4e5db
Create Date: 2025-06-14 13:51:45.923581

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e9c18c76fc2d'
down_revision: Union[str, None] = 'ea8382d4e5db'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - Manually Corrected ###
    # This block was moved from the downgrade function
    op.create_table('races',
        sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
        sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column('ability_score_increase', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False),
        sa.Column('size', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
        sa.Column('speed', sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column('racial_traits', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
        sa.Column('languages', sa.TEXT(), autoincrement=False, nullable=True),
        sa.PrimaryKeyConstraint('id', name=op.f('races_pkey'))
    )
    op.create_index(op.f('ix_races_name'), 'races', ['name'], unique=True)
    op.create_index(op.f('ix_races_id'), 'races', ['id'], unique=False)
    # The commands to create dnd_classes and class_levels are omitted
    # because they should already exist from the previous migration.
    # Alembic was confused and tried to re-create them in the downgrade section.
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - Manually Corrected ###
    # This block was moved from the upgrade function
    op.drop_index(op.f('ix_races_name'), table_name='races')
    op.drop_index(op.f('ix_races_id'), table_name='races')
    op.drop_table('races')
    # The commands to drop dnd_classes and class_levels are omitted
    # as they belong to a different migration.
    # ### end Alembic commands ###