"""add_items_and_character_items_tables_and_update_character_inventory

Revision ID: e9c82ed44bb5
Revises: fb59cd6b1d43
Create Date: 2025-05-27 13:47:11.735527

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e9c82ed44bb5'
down_revision: Union[str, None] = 'fb59cd6b1d43'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('items',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('item_type', sa.Enum('WEAPON', 'ARMOR', 'SHIELD', 'ADVENTURING_GEAR', 'TOOL', 'POTION', 'SCROLL', 'WAND', 'RING', 'WONDROUS_ITEM', 'CURRENCY', 'OTHER', name='itemtypeenum'), nullable=False),
    sa.Column('weight', sa.Float(), nullable=True),
    sa.Column('cost_gp', sa.Float(), nullable=True),
    sa.Column('properties', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_items_id'), 'items', ['id'], unique=False)
    op.create_index(op.f('ix_items_name'), 'items', ['name'], unique=True)
    op.create_table('character_items',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('character_id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('is_equipped', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['character_id'], ['characters.id'], ),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('character_id', 'item_id', name='_character_item_uc')
    )
    op.create_index(op.f('ix_character_items_id'), 'character_items', ['id'], unique=False)
    op.drop_column('characters', 'inventory')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('characters', sa.Column('inventory', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_character_items_id'), table_name='character_items')
    op.drop_table('character_items')
    op.drop_index(op.f('ix_items_name'), table_name='items')
    op.drop_index(op.f('ix_items_id'), table_name='items')
    op.drop_table('items')
    # ### end Alembic commands ###
