"""create dnd_classes and class_levels tables

Revision ID: ea8382d4e5db
Revises: f664b4be65c8
Create Date: 2025-06-14 10:03:52.873994

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ea8382d4e5db'
down_revision: Union[str, None] = 'f664b4be65c8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - Manually Corrected ###
    op.create_table('dnd_classes',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('hit_die', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='dnd_classes_pkey')
    )
    op.create_index(op.f('ix_dnd_classes_id'), 'dnd_classes', ['id'], unique=False)
    op.create_index(op.f('ix_dnd_classes_name'), 'dnd_classes', ['name'], unique=True)
    op.create_table('class_levels',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('dnd_class_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('level', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('proficiency_bonus', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('features', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('spellcasting', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['dnd_class_id'], ['dnd_classes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_class_levels_id'), 'class_levels', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - Manually Corrected ###
    op.drop_index(op.f('ix_class_levels_id'), table_name='class_levels')
    op.drop_table('class_levels')
    op.drop_index(op.f('ix_dnd_classes_name'), table_name='dnd_classes')
    op.drop_index(op.f('ix_dnd_classes_id'), table_name='dnd_classes')
    op.drop_table('dnd_classes')
    # ### end Alembic commands ###
