"""create monsters table

Revision ID: f664b4be65c8
Revises: fa3b08d8e32a
Create Date: 2025-06-08 22:02:11.178667

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f664b4be65c8'
down_revision: Union[str, None] = 'fa3b08d8e32a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('monsters',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('size', sa.String(length=50), nullable=False),
    sa.Column('creature_type', sa.String(length=100), nullable=False),
    sa.Column('alignment', sa.String(length=100), nullable=False),
    sa.Column('armor_class', sa.Integer(), nullable=False),
    sa.Column('hit_points', sa.Integer(), nullable=False),
    sa.Column('hit_dice', sa.String(length=50), nullable=False),
    sa.Column('speed', sa.JSON(), nullable=False),
    sa.Column('strength', sa.Integer(), nullable=False),
    sa.Column('dexterity', sa.Integer(), nullable=False),
    sa.Column('constitution', sa.Integer(), nullable=False),
    sa.Column('intelligence', sa.Integer(), nullable=False),
    sa.Column('wisdom', sa.Integer(), nullable=False),
    sa.Column('charisma', sa.Integer(), nullable=False),
    sa.Column('proficiencies', sa.JSON(), nullable=True),
    sa.Column('damage_vulnerabilities', sa.JSON(), nullable=True),
    sa.Column('damage_resistances', sa.JSON(), nullable=True),
    sa.Column('damage_immunities', sa.JSON(), nullable=True),
    sa.Column('condition_immunities', sa.JSON(), nullable=True),
    sa.Column('senses', sa.JSON(), nullable=False),
    sa.Column('languages', sa.Text(), nullable=True),
    sa.Column('challenge_rating', sa.Float(), nullable=False),
    sa.Column('xp', sa.Integer(), nullable=False),
    sa.Column('special_abilities', sa.JSON(), nullable=True),
    sa.Column('actions', sa.JSON(), nullable=True),
    sa.Column('legendary_actions', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_monsters_id'), 'monsters', ['id'], unique=False)
    op.create_index(op.f('ix_monsters_name'), 'monsters', ['name'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_monsters_name'), table_name='monsters')
    op.drop_index(op.f('ix_monsters_id'), table_name='monsters')
    op.drop_table('monsters')
    # ### end Alembic commands ###
