"""add session notes to campaign

Revision ID: fa3b08d8e32a
Revises: a075cd5f2a45
Create Date: 2025-06-08 19:48:05.886949

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fa3b08d8e32a'
down_revision: Union[str, None] = 'a075cd5f2a45'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('campaigns', sa.Column('session_notes', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('campaigns', 'session_notes')
    # ### end Alembic commands ###
