"""add_has_expertise_to_character_skills

Revision ID: fa6d854216b3
Revises: 62612bd065e4
Create Date: 2025-05-31 11:50:20.239648

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fa6d854216b3'
down_revision: Union[str, None] = '62612bd065e4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('character_skills', sa.Column('has_expertise', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('character_skills', 'has_expertise')
    # ### end Alembic commands ###
